minimum_prek_version = "0.3.0"

[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "check-yaml"
args = ["-m"]

[[repos.hooks]]
id = "end-of-file-fixer"

[[repos.hooks]]
id = "detect-private-key"

[[repos.hooks]]
id = "mixed-line-ending"
args = ["--fix=lf"]

[[repos]]
repo = "https://github.com/Agilicus/pre-commit-hook-k8svalidate.git"
rev = "v0.2.0"

[[repos.hooks]]
id = "k8svalidate"
