apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - vpn-secret.enc.yaml
  - pvc.yaml
  - bjw-s.yaml
  - media-stack-helm.yaml
  - recyclarr-config.yaml
  - recyclarr-cronjob.yaml
  - recyclarr-secret.secret.yaml
