apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
    namespace: media-management
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:swOYhRDcoCfVKYiBnpyLAPg8C9+lDIwI10cwm0z9ao8=,iv:4CP8jlPTVWyH9YTDCYHNIJza4s1ClGZNy2MF07JCSqg=,tag:bVPXlZhauLdFG55zeZzR7w==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:pUbsKdb2xpx7D/mL3pBIi09koiIaG8wxaO5GAKeIiH8=,iv:21u+v+CivaqLtdjUrTTG1dWXbwslwPQqmAWMcDQlVa4=,tag:E9Axq6bX0YtR5xCYpsrv9g==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0dnA5TVRqT0xYSlhBL0d4
            dVEzR1ZxZGlCckQxNy9GTkF0bm5jRVBCSWt3CkdETzZra0pOTndFWUk3OVNISzRH
            YUQ0cEhGZkxrVlI5Zm9Oc3Y2Q3BXcnMKLS0tIHBnV29tQVcxQ0FCcTgxR3hLRzhS
            Q09UM1JURW81OUZ3c0lKMUJrT0tMc1kKuVq4/8os3skhMgBh69SVxUxVs1RWOd6S
            cMTnbjc68So4OprwmoehP9toHoIbPhP3u325Khm4OEnUrXr11bh+Gg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:43:18Z"
    mac: ENC[AES256_GCM,data:N4M6iuovpJmMPJvrwJ1RXi6f57WaX8hpHbyxsv1DxEL2LaI4O85SmMkiQUXozmRSZ1F6FYcXUygahQdngOUuGBKTXDYUwPdfEK9vlP5zdYLdew7cj4k4I6XM8wjTpKXI4lTHgSliYOkVEPmY2SwuG2Z84Bof4JQ3XlnRgQbYc6Q=,iv:281RzHqM95tNF4WUerFT/FQRH6f+Eks9fd4G8ri92Zw=,tag:ZkXUtZUnnADP22eRMcs7lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
