apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
    namespace: media-management
type: Opaque
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:ea52ysrH+QtZ/bN26xBHPKx3BISfrFz8AOXzgYWnv/o=,iv:7rnc5w9R0KXR0IBqF2GI2T76I2a18a2vprqYayn3Go4=,tag:ql20wbn33k9IQ6ONrtLFFg==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:NBcLq7knyq52hYoIv+xSChOyMO543JHO0nYdXGU8HXw=,iv:xWWj3AV3fSBRoD91r8MwOe3wSp4IWDVEN5dRzWfba9s=,tag:3nF5skNFDWtuLqVKSZ7H8w==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeDRmeEpTZEJSaGVlRk9s
            QVlCd1BIa2cvUW9vOWszeWlWdVJ4UU5qanprCmE4Umc5MEpvOEZON1dyREZOV25B
            cW1uM2Nxa0xjQWduckpZbkx5UGFZQnMKLS0tIEo3d3B4cHBXYTN5NUpvLzRaOEhU
            VUIyd3Buc0ZjeE1sdmpwQWZQNkFGUkEKfzfRuCqNEmeUYAw9g2V9Sm6BY8LdAWbW
            rfO2OHDzFib4XylKLWLtgcNwPavsYV/mFnLtHZGoRrDdVjatjPv04g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:35:39Z"
    mac: ENC[AES256_GCM,data:UZFtkaaWavFx6LBYP/IJFaj1ymoGfTBN0ttqa0+NcqsrTXmgAazvTVarsuaSgFuNZYi435XuT6YhlIgFqSKblIsZr6F1VNI7kpYun2T/hQC4GFiI6Ue98IXkKixTsCA8RZENUF4lqIHPahaAShaNvs0afea6MEttymejLggbrCo=,iv:M5mAG32UvgDQJV22+SOTy5cJltuckdOcS7LRZIFJNog=,tag:ZwG72SPxanTpvWIXljq3AQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
