apiVersion: v1
kind: Secret
metadata:
    name: vpn-secret
    namespace: media-management
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:9vKwTldxVoxXaQE3TsCplHHseyU5O/7yAIN1bhBsCw1L+p9QebfGMnDLkns=,iv:Z2KTvU5kMQCZ5TOyfIeDnsP3dBWPtjFdGJvTiLHIZrI=,tag:xGzJFWlu0Wa1/Zn6taj6jg==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:rixQa4SkO2WXEaHqhNs23P5y2B8bye5ld06WoDwxsPKXHgaM7MWD+6eea0U=,iv:UnDLy94oMEUBzLJqsl4fZiOxXwzYHv1a8LYKCiKzovg=,tag:BPhSCkoPqFAqMBQiN/oGdg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:b4JMS/39mJjINCDRCfD9hQ==,iv:73/tmDNBvYtH7M6UdvPQdnXB6RKpaNicMApm1qnm7Tk=,tag:MuhC9i/ebjVjn3rN9wbsWQ==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:KhIgaaVyXJcRPlcBg9lxaZ0=,iv:HhI7LK+rP19CXnetRM+yQqBmUdKMB+rCI0gUds/oKiY=,tag:lqx/8eBEmv6AX5rLj9eQWA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbDRWc2hyb05kYUszMm9k
            TmJlQUVMV05pN2NkcjRzZkhNRVNUVWRiSHl3CkdKUDliZEF5N3JObUE4YnN5MC8w
            OEI4aHlqdmNzSUVzcU5acENPQ0N6TkkKLS0tIGdPODNPM3dvWXV3TC9EdUJyQUVv
            SHBvZEdXS3JaZUJaV0RKcFpla1FvTFUKIwn1qMDPIl6iCGJSkZvBCrPkgZ0g/yY2
            Sn5bGo1vqk0gEkSg64HIKA5Fyi4PxZ3J83jYyWQlLASRXxCwXMIr+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:43:18Z"
    mac: ENC[AES256_GCM,data:QiNPLQlJUDj4Ix+DmWSKrzymgcEl5P9IEg4kKs/VucupJzf67yFvZ0VMrOvt16xjbOA+k9EJuuaiYFsOYyFTHBKxaCrypW0s4p7xR4IbDfBH/vGoOlNVHimACVs92tGZxcBkJ3Phc02Rdg7r35oeHRk/9TmBEezR6+WHiKOMmMs=,iv:7UFzdJItr+R57wbNLgbnQSCl8Uy5pU0vUy9dVchMMPg=,tag:kfQG6bh09dt16aQ4z9pEcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
