apiVersion: v1
kind: Secret
metadata:
    name: vpn-secret
    namespace: media-management
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:rOeGj7gzPidKUu2csWTLDtS7h3k9B7jKJ3Atl2RNjs6EyWEbATN/Skmp16A=,iv:yDQJ7EihuG2IyKKe6ayuCozcWOWyfgYYWmGtxrTEHow=,tag:yyVi1bdO5UzZz1WIuGSXDQ==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:Jl8EsshCaCpE2spRxqcwPmfX68u903ionBs0VDpmkau4uYDOk9eFjmObTdk=,iv:j1thyBs2HOUxk7gLsZv9+o36hKwZlHdOlpHQIp4FGoM=,tag:2G6WyY5NxSUrlQJTNIfR7Q==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:+yEj9GFHPCFlzV+mlOrIyA==,iv:rTWA/fmodIIN0ZWqUGdibfoNThBa5Lem+mUSIN/DT8Q=,tag:60lSLOmjJ0Bb6sTDE6ohrw==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:ZYyK34dh0XgRlGOzJAX5NTA=,iv:Z2lrgkI1i8mp6RvgX5I/ZRgUGvs+Dy3oJJVPZLWhwkQ=,tag:qUr1OMqsKWZHaFgdBfLPiA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKOTZpU1FnVHUrTUlpUUxz
            L25tMTR4V0YvWDY3R1l0ODhtODM3dTB1STJrCjVadFF2dTA4MmYvSUozcnpPd1VT
            SHJCbmJZdGFrd1Y5ZjJsODdiKzdCaUkKLS0tIHhaK0lWQTlON3p2ZWp3VGw1a04r
            OFhsYkF6RUZ6VzFvZm9EdjRyTFRXWlUKdeWfYRhoJTt5rJqqnbZ4QcevOKjL1tiP
            wejEExKlhfbI0chQNQ8fTZ98B/oh6NQ+rwHDa8+P8C6gtrXcPP7Hkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T22:36:56Z"
    mac: ENC[AES256_GCM,data:CsLmicx3EgwGVCdlV3vGWEwR9pwl+GD7kLZFE+m4RDfZtjG6J6ZwDxZ/AvqU7busvYa9PX+eYTXT1GmHTcBTlGUhyh7dQEiHc1AsSwoOfCC6rkRErd4KddaepfiWKgza27fAyc60me0qoO2Lt9Bvr3un4MR+Mi6q+rEH/Viu56s=,iv:dVPQ7Y45y1m5+zqKtBf7+V/SvcvY53w7MbhTGoNfeNo=,tag:BtSOawssDD+PU00/fWiwIw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
