apiVersion: v1
kind: Secret
metadata:
    name: vpn-secret
    namespace: media-management
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:6ddlLqrIv6il0Vv3UlUAI2hgImI1yFu3KG/Cf9tTh6ui2GrJqanE7iaCU8Y=,iv:k4A8bHTuztALzWzyb1Ts/KsMN8yyAxFLZEKZz9yir+Q=,tag:y5K7nFOEh6QPCyRNRAIX2Q==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:8ofv69+nKug15DXLa3uI5Fz5FoipfghcMTTxgpDT7HevCU9Y2CYqb3TIT2w=,iv:cb2S3+PufRIOYU9XLDLbxMvHJXKKsVmAfYm6UDyHGbM=,tag:/mWsOEHa6eHaDdkd6qNrTA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:lHtoqkLZlBY6i/4sMJuvVA==,iv:uMWN+K159U5vJSXRhIQZq/I2hxqQkJ+lkgvZVzgjyZg=,tag:stxkgZUG0QjEcqEhkAOQZA==,type:str]
    SERVER_REGIONS: ENC[AES256_GCM,data:6ZZrp8l7Gb6Qb8IDPatKSOg=,iv:2atxzgvvf+3lJOlfQULDH2mXVBL6gcFIf2vSSNQIRJg=,tag:FGSqjL7Aj+ZIgPY6lo8wOw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzQ0QxbHo0Y2NvZnZER0xO
            RmJETkFqN24raXhqVmI3Y1Vqa0ZqVGEyNGtNCjVxWEV5M3p3SE5MOW9UTzA4WWlq
            c01Ra2U3RTBLUVNRRkNwT1RHc0xDZjAKLS0tIGY3SzhjaUx5bzE0VUo4MWRlaDd4
            N0hMVUJWdW1Dc0NrSTlKQWczZGxUbkUKcDrFWB4XlFrJdr4pISOeTGUQyxTL1x7o
            Gcz6G5eSJ4yDMheLFX2Igigq8DF0TSk/BL2R09yEiB5n3HN0xIK+qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T09:43:56Z"
    mac: ENC[AES256_GCM,data:bx/Dc6in0e7xWiPXJ9Q51T+lanzqh3riu//+wFRd5RP38tV74Ujev6sG1m571ydAH0Czeq/daF/cFaKxq745QxkZrFWC3/Ql+tJnF4/UKNQ7N+dm6dREWyDHtD/kygxW+9LUbKXwg2wk7KtRX0Up7MIEhzsIMm3DFfrcTt9KXfU=,iv:jZG40RlfBoBcBd0TcTKUeHI2Ccps6F0OYEHz8VsVOoM=,tag:SR0ywyupNCQ9RzaQszSvjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
