apiVersion: v1
kind: Secret
metadata:
    name: vpn-secret
    namespace: media-management
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:TpB/ncQkywLQdDbhdB4BvmhhAiNxA5+YLTvEx4R06B+/VrpP8brqmtagfpA=,iv:hDzhzRbqjuLmcmufoLY+evUcdVzCQNMTJX6wPyytklE=,tag:WGCUlgov1byD3PAqmnr21A==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:JTNm73i5GT5BpPrvNEpqvE/FSfhLUMC5yb5PT4gHQIP/2Q8B2Erx2AMNiQ8=,iv:7O3LFYBBgsj7K9QgyFPxy+K0PgzR/uxl+ec9gsQnuQA=,tag:4XRdXT5otaVo07HHEnPQgw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:Lxz/SmNR2/iKLK0b9iLvDQ==,iv:iZNFyCJMjYYPTCuWqy8mgEHsH0J/pG0XJLYc5tS3teo=,tag:894urPQ1oVKBXbtYPJbK/A==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:lGEJ68QCnPLDpSzfQ0OqRLM=,iv:n/FH5HBaohufWyJKH/3Y3RTIdHbgRuztMNbkDyBNIRw=,tag:X6I1ocRixC4LuvLC+MXBNQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYK0V1K3JOcTg5dXR1R05r
            YllQRU5idjhqczhwbG5KSnRNSE90bzJLYUFRCnN4aWJSZUJNU0dTZWN1bU9XQ2ZX
            d0ZPc2s1QUNVQ2FyTEtaYVJRc0QyUnMKLS0tIE1ZTzVOQU8vS09PT0ZDeVU1T0hI
            K1k4cnc2RklsK29KU1BMbitkYU1Zdk0KtoxmaAyPcoMBLXsfbD3Cl1is1WyWybAf
            OV7xsaiNkc0Y4AaqiVdgvBbEAGnl1z11CFY7zHjrE7CjrTAJvh8A/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:25:09Z"
    mac: ENC[AES256_GCM,data:MtrSXhQh88OtT2rpsH+habebMx8nxbL33jXkUyVsYvHzsoo4NCbXnkH7q7GPRJ0GmhiWDoEJRWsIUCZf2j9/vJFQIF/RNYDmRLU2lm4KLJNsGdB0VejOfrnwfLyUMXvyKxawMpfmhsxEWF4vKHY1nkksvM7seytY3tTdeJ7ogvk=,iv:b8Y8JSkz662t0fIZsGXw7/5aGwMJNqSp3lOgiWFRwNE=,tag:wYxsiXbknC/F6SIpaSocMA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
