apiVersion: v1
kind: Secret
metadata:
    name: vpn-secret
    namespace: media-management
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:fIK18IT3KvCVhWpjOQtHCorLbsgGcM/wKRzOyKm86xXaplYYz8oErVnQa+Q=,iv:GusJkNX25uo+90NI/0oyEqJ456MTqXsRFlyLx8u1r1Q=,tag:kNYCVS93qyBKWPLFotySBA==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:gytOEwkVXbzwqwSKvKRYzfbe7r+T6wX/cKQ8j4RfrPmHI3ilERcL2Mtkmuc=,iv:dU9Q4gBof5CafdDDKi1b2l5zP3lhxCswBaZqMpOm5qU=,tag:vJy29JJ3pKK+rWWMMJgxng==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:Yg55dpqME345i/t3+4Fygg==,iv:XAS6L3/RaZnVGspGxFgCQ2zT2Qa+TdsZp37QIlvxN1Q=,tag:r/SF3YUdYjcA7Puh2k3iPw==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:58tNrkfDjXgHcvLkvme/f+w=,iv:t61grcmKknfwoRyAU5wiBlWwL8DsxvBoipWQWIxSZxA=,tag:M8OGb7+CMR0xVV4b/OQTOw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva2dlUEc2LzNJYzFRUEhM
            N3VLTStHQ0FQRVczU01zMkZkZUlHQVlTVFRRCklBRGVZa0JjRkZDZzd5WnBuSmhj
            UGVCcHdGZGFxaWJ2ejN0WmUwc1l4aGMKLS0tIFlpLzFzcjUvQ1RkVkxTOEYwRCtz
            Mnl6Wm5TM2krMVBrZDh4SVRjVUEyL0EKRHaXr0bAsMf6m7XCt4Ci48OH40g5L935
            bE4DaEd7FZi2mZMeeiYpSxKKZZF+DyYIajo3b62AGafqiyPKvxasTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:35:39Z"
    mac: ENC[AES256_GCM,data:Zn8L/5XXurj8qysG6vlPwriMcwtnA2cIGhZ9UMv2qfvgvO396Wklw9CCmWFj1V8dvqwY5YnV0nj5BqFocLXtF07r4/OKchjRg7P4dlcBOqMZfhtzjyHZzhG9lMvjpw4zjJWDuV1u8I05adwmRFz5DZMvCNev00JvoLPeeWiliWE=,iv:7i+ml8yhcHzXN2D4VPNGurWtyyZzvPissZIiSet23m0=,tag:UOsMH+6fjqrmaEMyeRWowA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
