apiVersion: v1
kind: Secret
metadata:
    name: vpn-secret
    namespace: media-management
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:UHl1aXY/fz9KBeGH8HLWHQZbzaoJ/EIpwak7Ae8WI5zWa5vlHEZPLCjOIoY=,iv:m+I9FsgoCx7q/yggsI+xnnkVUq++N3SyX+BzzL2GAiQ=,tag:AF2AbkslvIwRxrQjEZGHmg==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:sJhOdSBDN/8ejmh7tdXfvi0Cs3nGLiz8XcgWpzVzpUf+ZRYVzINULQqhoEs=,iv:J4quTwMAbpY2dksyfBRE5p9Cy/41GOk9RxoNAzmHQ4Y=,tag:S7VlNZoXHiXArKNmPj+Wjg==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:65YDC52E/JawdkzhdLNUqQ==,iv:QxfFmUAfM07Z0Mydh+Jwmh2b7ALic2eAQ7HjdVA9m4E=,tag:SDG4yR+d3O/FTDIVQfEz6w==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:da1Ubn3HgvxeDYLoUESHxz8=,iv:dtzQrQPfyNk9FN8EOqPKr1T7gCfIZV/UO4jQJsh6T88=,tag:M4+XBTg57apSlO0HWYWyxg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFaWFRMDZJVXhmci9UeUJS
            L3BUalhHRCtVWTIvTXozNjNUZGVwU0dpc1ZrCklwUmFOYkRFUmJoOW1MdTBOZE1M
            NTVNVnlWMkhvbUZyRjNxRzFVd201UVEKLS0tIEtKMGlhTy9GanhCREZMVk9VTVc4
            STRmRHd2a2JyOXhUbFpPNTJKdjZNcncKWPcwm87r2nSBZPInS4R+S02Rk/KetaMW
            yYN/3WLWFlvo0F7e0rHSCw0FsDHGBMH+CH4iKrTIvWcXErFshDZOxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-29T13:47:55Z"
    mac: ENC[AES256_GCM,data:6Ml4BzYjllRg40ITFjoU/O71dSNShn1/cFd+c8+dnHvocFHREnWa+CbzWxBgSh/YE7KAx0F7WyKZQSFE2FAizgrEh7bK91SKeODPFz+y+yaSO5pmsq+VTPuxfYnV1b7bM7WlFPSfooTxQmsk1h+ITk5mlvt2nKkQgoR60wW89F8=,iv:2S4mxuYuLMBEuE3gQqMgiy5QDpPv+kdz1yA+pr403uw=,tag:MMp8oTCOEAvG5Fwd51BfAg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
