apiVersion: v1
kind: Secret
metadata:
    name: vpn-secret
    namespace: media-management
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:zWp2DIx8+lrL15aqllN+cdFX0XYpoD9OC+H0Sxe0L7IAg8NOPdo4btnUdOs=,iv:yKqqtZ4TE88AnlO0aaVLM1wreU4P7pneEH9QgIy04OA=,tag:5hCUahLVHPEu20FFNV8vrw==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:+mvsinZ3WUMzFdNpRE2K7Yuy9+7zWRX1BipXcgGKUzF7Zf5iWm5uy3Hxse8=,iv:Yuk8spWwYJ7eZCxzZQF60qK+HXIlM+PleJHbysFTkRc=,tag:ACpSY2ZFhr6pBVrwMml9Tw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:hHCxFTtddhiclSEjfdDzYw==,iv:wYpsHtg/FRVI65vBXc5eho0IZLjekqZ3BhBT3/lbqcg=,tag:k2wiawmDT9Lpv5e24j4BhQ==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:XrtOV1/7855NXsHVQMqjlP4=,iv:FM9CHgE95HvkiscUbmc8s5Gqzq4mPkdT55ac9e5T89s=,tag:R0W1f/WYeHwkDiWzZfZ6gw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1V1V2Z094YnBEMFdVbTY0
            S24wakVQaXYwbHZ6b0xKdW9yR0ZhQUczS1dFCkFYK0FjdVY1YTdPR1kyVnA0cTlj
            aWloS2ZtR3lYeXZWKytOV1hwaUdBdjgKLS0tIDBQTEpIQkFxU2dtQXA4aThuV0lK
            UkpsS3Vjai9vL2RFVVVyU1JhcEh0d1kK8UKmA3crmVblCEtvr4/OZApbhfvuaamx
            nA86nMVtYoY9qJTt9aD4vFaFvpzmvYp9thDAmGefxj73n2aEBqE3cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:34:09Z"
    mac: ENC[AES256_GCM,data:jI7o/Fe3d7wco9JPh8Zgjlf5pGgBF5tyy4rZ/XZ4sJnmi4n0Ky0leBVyCTNUhS6Z/a+LSr+vfPrJ0nubY3McCRxInbvfHN6Tgxa7vGafoY0202OBKqq5ts1hBHUSUaw98SMsfdgtpoVAqUCMdAcFgDIwpUMfvZYCmeu0nvZn5CY=,iv:r09DjazoupC3wFxkkNbuEk5sF67PGIia8iDOqvZ3xqs=,tag:USIp6M6MMSLgUppgj6fEXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
