apiVersion: v1
kind: Secret
metadata:
    name: vpn-secret
    namespace: media-management
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:DZT5y0hcfubM+wgdPRDf/7YoMXRVPg8HOTnNswZf3/F4gKrBe1VIYarGe2I=,iv:5catzt1p9v1k5JeoO6A92A16c4rWaNeI0BhrHic3gwI=,tag:JacsoTdhqQQMT6A71N3jew==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:yEM9QIRxDJVfkXq2hryHm5AW5IZSzGSXDLbtA35su+PGoFMxXgB+rXCTOc8=,iv:wfoUmvyoVNYaw6P31m1QHq80YQOPEdTVJneCXJ6qhww=,tag:Igex2HXc2hBj21+MT6NJ0Q==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:oDLZpZJUqnOuFWSBeuBV7A==,iv:nwYLv5wC2ZnzBEkFvSGpnO5jGhJbZgecmITcMud/uKM=,tag:quwKgjnt/8PyxksoITApgw==,type:str]
    SERVER_CITIES: ENC[AES256_GCM,data:5gZkEwpWP8nEQ100LGmC4uo=,iv:/y/jZ7PBOgmEdmuv+lLZaxoqMCLcj0cdOk9V7Dll040=,tag:/9HF4yagzXh3ixJJjGcoXQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZVW5sMTJjTStndS84ZExk
            L1Vsait6MVNHeUx4NzluZ1RxcVN2V25XVXlFCld5R2I4VlI5V09NUFhWNEFTeEV5
            RzQ4U1d2NWtlbzVNNGU3MXVOS01yZW8KLS0tIEFWTENqdnRmNnoyT3R5SGJYY1kv
            VDdoNXBFekNjaWxqanQ1cDlTVnAwTHMK8O0IMJNERQiQ4EIcryokc0MTcGx0VH3A
            lb40r+VN8sqcJwYuLcQAFzsqpujEfAyP7kbE/8zxBdlyUR2q9SupHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T18:04:40Z"
    mac: ENC[AES256_GCM,data:b4+WnamKa+Byz3feXEVwsij/rGpPoEXZ1hMC6Vnld9xCbNaX+PLXp1VfopcN2ibyeButLpM81oNZPQghuxtM7lbrYMbJhXt2VAVZ5Q0zyQED3XrfcaahAJq3UjeaGpY2MXeoIlVpvQ8j6MYXkKu1mf23Vw/PVPLWKKpahuUDxqI=,iv:FRP0Qse+GoFM5g8ZxlnC0Y25nV8bQJCN20ITz48ICg0=,tag:DBA9eFPa6TB+CCL0Lmlrwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
