---
# ServersTransport do ignorowania self-signed cert√≥w
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: insecure-transport
  namespace: traefik-system
spec:
  insecureSkipVerify: true
---
# Proxmox
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: proxmox
  namespace: traefik-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`proxmox.home`)
      kind: Rule
      services:
        - name: proxmox-external
          port: 8006
          scheme: https
          serversTransport: insecure-transport
---
apiVersion: v1
kind: Service
metadata:
  name: proxmox-external
  namespace: traefik-system
spec:
  type: ClusterIP
  ports:
    - port: 8006
      targetPort: 8006
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: proxmox-external
  namespace: traefik-system
subsets:
  - addresses:
      - ip: 192.168.0.9
    ports:
      - port: 8006
---
# Home Assistant
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homeassistant
  namespace: traefik-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`homeassistant.home`)
      kind: Rule
      services:
        - name: homeassistant-external
          port: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-external
  namespace: traefik-system
spec:
  type: ClusterIP
  ports:
    - port: 8123
      targetPort: 8123
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: homeassistant-external
  namespace: traefik-system
subsets:
  - addresses:
      - ip: 192.168.0.30
    ports:
      - port: 8123
---
# Portainer
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: portainer
  namespace: traefik-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`portainer.home`)
      kind: Rule
      services:
        - name: portainer-external
          port: 9123
---
apiVersion: v1
kind: Service
metadata:
  name: portainer-external
  namespace: traefik-system
spec:
  type: ClusterIP
  ports:
    - port: 9123
      targetPort: 9123
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: portainer-external
  namespace: traefik-system
subsets:
  - addresses:
      - ip: 192.168.0.15
    ports:
      - port: 9123
---
# AdGuard Home
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: adguard
  namespace: traefik-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`adguard.home`)
      kind: Rule
      services:
        - name: adguard-external
          port: 8012
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-external
  namespace: traefik-system
spec:
  type: ClusterIP
  ports:
    - port: 8012
      targetPort: 8012
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: adguard-external
  namespace: traefik-system
subsets:
  - addresses:
      - ip: 192.168.0.15
    ports:
      - port: 8012
---
# Qnap ui
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qnapui
  namespace: traefik-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`qnapui.home`)
      kind: Rule
      services:
        - name: qnapui-external
          port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: qnapui-external
  namespace: traefik-system
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: qnapui-external
  namespace: traefik-system
subsets:
  - addresses:
      - ip: 192.168.0.11
    ports:
      - port: 8080