apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    postgres_password: ENC[AES256_GCM,data:28gom9kLmqIcwrNkVYH2k/IW6iCX+KjTY9W3Ob3fiiV1I2ylSAST3dyP8gU=,iv:E3wstR/+vfT7ohPDpjdRkth1pffE7LCX3diDD1TKnMQ=,tag:HkO9rw8fBtVtAWb3uvaaxg==,type:str]
    secret_key: ENC[AES256_GCM,data:1Zsii/dQVhZKyxFRb0S3VsLzqRT3I96DJ+YBoW+tfog=,iv:WWRS62GFxiiqF5KoOHNo/EGR7EtRuLeZ83XtNT2Y6tI=,tag:ZPncnB8/Grc6Jph8Xwe7Xw==,type:str]
    resend_api_key: ENC[AES256_GCM,data:c3qL/FY617hXSb3YcvznG/QfWOQbR2uwd1cn0yjtEVSefzRz,iv:vwlLiSWueqLpb+OrU8iVmGXnwazk4heFSgEA3JpO9no=,tag:xPX673T0ktuzCNl6ZXTU+A==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeWNUUUpHelpMRmNZT0NZ
            SXFVZUt4cFpMMk9rMTVUbkJkYnNMZGgwYUVVCkMwVGhMVGd5VG1rbWlPNDBZWmNn
            eXRhMktQU2hPUzQ0NXN3dFFGSXJrancKLS0tIDkwZHRjdzZCS1RTNnZ3L21KNGta
            dEpLMXBzVkN3RmJpM1FLY2pDOFU4NFkKwuSCEmePM5sMz0FBJulArS4K+L755mx6
            vGYJ11jrNEXTHDSmZLKgkolsgNufidMh90b14Z9IlFdvEnIVvqN+xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:43:18Z"
    mac: ENC[AES256_GCM,data:Kq++4Rltbkqa5TsmZSeSE2RZllcRQjIIuuB3myCdKLmT7sQOd04oEWzk/ILfqICmRlDofE4/zHp+KHeePrW2Vd59ecsU9g1C61VzE4z0HVg970vUMGw4TPw+rW4jioZdD9fxWAdTA/Eo8v+EHxNqes6l+JCbX7lJog86uDSe91o=,iv:QKN4NipPd192XCwfta4Xb3zeAj+cZByZbSTvUCa9quA=,tag:ZCa+Uw09H/hd7MZmZ552SA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
