apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:6ry+E9zoaEvj6sYZr1wAkkcohFpXUfWgn9A2+OkYDaXxcYdYaKdEim5ZwRdqrHwRQqDi/kUK48RVJ/qp0YfIeA==,iv:01mf9BLsAf+lW/KuPacMP9k4Nf7XUE6NbOdwOCfc0uE=,tag:BbwXwslWRkQAltvb0Hk1uQ==,type:str]
    secret_key: ENC[AES256_GCM,data:Tey/C99JYKvN5QFRVqPQsLsOTTFy6WTuQ83obdPx3no=,iv:uTIZ2YMHnFGcz/ZFSEuRI1xdzrBZ7WRTFQJQTRl2QRU=,tag:nj8xlVU57TokztWsR4xb2g==,type:str]
    resend_api_key: ENC[AES256_GCM,data:BgmIYnM1jcxkbSXFT1EGU8wZP2/Zv9Df4az7AveVWhVOahuC,iv:AVsR/bFUo3Ijow4a0po2rK+F4vpRxLGMiT9YCzxJG30=,tag:cdrb5x5nOGU1JqMJEqpUQg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaWJMWXg5c1BXSWpsRVBy
            WUw4QWFsYWhXR29lNlpZKzIxdFZ6QWlCQkZBClZmVVc0MVJwaDNBR3R0a3ZzZmZE
            SXNrOHNUVWd4aXBoeGZEYi9rYlJXWXcKLS0tIC8wQ1dLaVRXNjFENUUrT3kvWXlG
            NlN4SnhVZ282ckQ1bDlkRk5kengvY1UKiygjEA0/jfCbQ4UV52DDF/O3EYrH28yU
            AbQhhjvpicux5PeNgk5UwlEW0xS6FzctvJVv25ebQ4SbcbJarIzORQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:25:09Z"
    mac: ENC[AES256_GCM,data:wOZD3G12SFYjFzXuYHf6eeWemdKRY35//wxAUVlsAp3FPOx8X/ODoaIlTi6Qe0sZ9k+l6Xip3PsibvHwBepFOiZD8ciV0VbDYGunb3W/hT+ywNNQ+Va4qdviSaMmCgec+wov+oMCt7lync5nGLqfedRxFApYzZ80dHX6tOb+saY=,iv:m1oZoUCe8mYDKb3LXXP+dlRHi1HaCC8qC73yhq8Eu0s=,tag:1BzfnJtqZxasvzJpIdWlNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
