apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    postgres_password: ENC[AES256_GCM,data:bDBMXwlKWLYIqhcj3fy6STAjTEbjGOXDlNdnTMp+Yh0oymTd12nrkolfy4Q=,iv:9USFMPAbpxBTB+7HzGUpT4lbgp3tExdjzabepj13+tI=,tag:YjIqVHs1zB9kuLKLpGQh+w==,type:str]
    secret_key: ENC[AES256_GCM,data:5rKdJqzGXt+NUfYwMd/uEpwRv6P7MzD5CikSpsBqLag=,iv:bGZ5kDrOSOAXPA0DIpDgrc71f9A8UG1IHU59FLY+Kwo=,tag:Kr9EO0+aZjKgG32ugL0KPw==,type:str]
    resend_api_key: ENC[AES256_GCM,data:gPY+SjVZIIwmhNTG669Gnu3sg/vreryUItRs3bRE3AGh7l4d,iv:Mz8vpU4Ohvvykjb/rIy3hkKds7l5vdhqiJq+DIw8P98=,tag:R6epIPskDS2cuZoV3umh/g==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Z1pJWHRndXJaZnBmV3Ba
            VURhY0hTdXFBdFhQYnNGeFpWRkdibkFnNlI4ClFaWmtGODZlYS91ZWZ3ME5rTXEz
            TVdLenMrcjZneDUzbG9CNTJFazBSOU0KLS0tIEVXSlBhTmREOFpMRVhZbm9uMGRm
            bUh0bU9uTHF3NUVLdnU4ckM3VW1vOGMK5tIz7pOOVo9kXhfdfTD1Vx36WRQs75Fh
            iq7Z26elqAzTi8k2OE6W0foN7n8rPfNX15KLyTz2nnpp/mMg3jh/Hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:35:39Z"
    mac: ENC[AES256_GCM,data:Vp5iAbgoZCLBPqGHHmpWIbe99+xUJ4OBTmlIgQcoifZcqvgRF2APZTMMAzI3CamxS5u39Xpvp9/92dkbZUBadjp0wdmsdGHEdtdtmaYl7vznkvWzK0C85ncOcm57QacmuLugTZfcroO4Yi+XL/Oouz3G+JBdQazmjh2/8dZMCa0=,iv:6LdwrumPF6YCFIWJtPNFNn18MuPkQi0PEWnrnooFmiU=,tag:U3suWM1unlqiYE2Sj03u+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
