apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:BEUgM3PQPYaVlu5h6B7L+07mF3EUKJZ2L6+XTLdFCo7Eg+JbJtYRK2e5lhZCE0sRDpM7jLPcOuM8fkuw2WG12w==,iv:mku5P/WaPtsxL1u62CsY/lI9lhzYfi9sMBqbfDebOiY=,tag:KRo+jauc4gQXi9ttUOLQTw==,type:str]
    secret_key: ENC[AES256_GCM,data:RWMLqUzPXRm627N1iU1qvhoiIcLXP/UkLjqpvYwGlLI=,iv:pz6FQmWvLWI2V0gUFYSAFuExkH7LFiL8fjelasg5Ilk=,tag:wtb3JNg6V+tu91HF+NbRqQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpaWpkQXRXa1BkdTROUWFy
            L2tJVmw3YUdBTzZYa1JlRXlrc1J2d3J3SGdNCldsa0lXelJCVHdobktYQWxrcUM3
            dWkxS0kwdGtscU13dG9xRGlmbG1RcEUKLS0tIE5QOEZvWEZzS3hoRC9kWFF0aDRE
            TEFlY1cwMjlHZE1ycGpYcWtjR1oyT1UKK4CTYkAn2yZ4RLUii0OKdlGaBhKJok88
            10ELVCYglUT19FTo8XbUzeFtBwW8nUaUf3k3ApPVO0nQl+ylgHivLQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T16:31:38Z"
    mac: ENC[AES256_GCM,data:NWws7juOzjHWKJ2irPBBU6nMWhfuPYWE2log+/BVqXm46DvisEP6F50h5luYXnm0mIMthDcbb0e6AWFFjOjdivJqmM7Gx+wsQi6h9oG76mtDRzYlIGjUuMXaOlpVW73IcuLXnYxK7Kf9jGAQGoKMpJipYQgOjZoQj95D/DAWoKg=,iv:Ay51kFkJRvHtwe6WNMf3501D+SzJ3fE1/IdNzDEVtRw=,tag:28Yv3rUxINOzcagIox83ig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
