apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.goauthentik.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      version: "2025.12.x"
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    createNamespace: true
  values:
    authentik:
      secret_key: file:///secrets/secret_key
      log_level: info
      error_reporting:
        enabled: false
      postgresql:
        host: "postgres-main-rw.database.svc.cluster.local"
        name: "authentik"
        user: "authentik"
        password: file:///secrets/postgres_password
      email:
        host: smpt.resend.com
        username: resend
        use_ssl: true
        port: 465
        password: file:///secrets/resend_api_key
        from: no-reply@emoh.pl
    postgresql:
      enabled: false
    worker:
      livenessProbe:
        failureThreshold: 5
        timeoutSeconds: 10
        periodSeconds: 20
      readinessProbe:
        failureThreshold: 5
        timeoutSeconds: 10
        periodSeconds: 20
      startupProbe:
        failureThreshold: 60
        timeoutSeconds: 5
        periodSeconds: 5
      volumes:
        - name: authentik-secret
          secret:
            secretName: authentik-db-secret
      volumeMounts:
        - name: authentik-secret
          mountPath: /secrets
          readOnly: true
    server:
      volumes:
        - name: authentik-secret
          secret:
            secretName: authentik-db-secret
      volumeMounts:
        - name: authentik-secret
          mountPath: /secrets
          readOnly: true
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - auth.emoh.pl
        paths:
          - /
