apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    postgres_password: ENC[AES256_GCM,data:3Eyob87dMNx1+LYyEhWtBIfX7uChMbgrScu6W95G/7aIY2V7SmotqkfLugg=,iv:BPQHTQXJTZsD/TQkaKOYZ3GxIdN/B84GD5E5o1quGy4=,tag:Z5LSy0BkvKHRky8a8gVEyQ==,type:str]
    secret_key: ENC[AES256_GCM,data:ubH+2Dvr9ZD+GX4NV/C3/daOrl16jjoz1sdkwxPQFsg=,iv:ZbDtg9ZsDqpzDkpkuGzTcL6Vk/TgTiDhPHE3UE5NmpU=,tag:V7Yj8rbuf6D7IWh6dJxHeg==,type:str]
    resend_api_key: ENC[AES256_GCM,data:kdKG3KbhQJ+t4RMz59gG1u9BxYtD3gL4C0tr7krHcOc7TlhC,iv:LdDIekcjrqUTccyfu/+dFlSev3zSb8dTdeFLhr2tmB8=,tag:mAFh37cocbtLhqK+Wp6FOg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZXk2MHF5bEVOVEl3LzRI
            MVp1bW1LeGZIVHJlSllDWmh6eTE2Y0xnNkd3Cm9ReitFWjhVTFRNb2NpUFowd0RN
            UHZhNnE5QWpBQ1JyRElCc2thT2UyREEKLS0tIG1WUTNaQVRZMWpPTldmNHc3ZVcw
            OUcrS3cxYk4rNGZaZDV0dHdYVmppMVEKMv1YIYIDLpajwpAmAkGm2/yK0fcJpX1Y
            +uBA4/B4XPIiNQRv65BMIjtC8cydSJheiXV+7pETQM7j3cFXdEge5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T18:04:40Z"
    mac: ENC[AES256_GCM,data:hpgX/NvwT8d9ggqXteUQqtP9N1ag7UbNa091j96w55zq0soIFPZViSEHpUJuEL7fJYyMlNuMFiWrFCzDCXSx9dAV1dXXzeQ7WzeSKv/jZKx9K8ecKLwmJOR7lPJxMOsSSeCuRYzOz2xZaWwEo7bQ0kaHesBW4aVpYtIc4PgVx+s=,iv:4ZHRV4NM6F0Q1wcr2jWUcxbFlEFRktvQso/wrCY9AnU=,tag:DIi7kl+bCaHktawiTUzK2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
