apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:W3ZhfYpUotMvZEzK9WEYoq8An55IqSNkLeoFTKrVfjjnPYfia+cLEbhDdEZGs4YNytEtLRYjyK0nw5HNoftGSw==,iv:243VEci9gGflZqWm6uQgBQdxtXQ3L3TXz1wTaZlub9M=,tag:ii+s+NOmxBCujMau3riaZw==,type:str]
    secret_key: ENC[AES256_GCM,data:cK4EYbNaknKTp46Uyt6Tv0w8/8JAD5xhiZwx+W3ksDc=,iv:J3oChGTV2P8kX6/L83yr8cX8JoCUQSMXAGsZBYeneME=,tag:oObzSkwlfaIh+OQsTSfHpQ==,type:str]
    resend_api_key: ENC[AES256_GCM,data:bAqd2NQFKA2cpXrAU8hy9+0VIPcegm9wZIOEes+2E034bRt2,iv:+1pIiCqlWqHpgSqGZFDUrzgOTdydAQ6CLQEYM+zBORE=,tag:P5rZ5G3iKt8aLEir1BVxpQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RWF5SmFjYVQ3b1M1cmNl
            dkpCL1pwN2xSb3RxL3YxdTVhVjRnakFCYXdVCk1XRDhwQ3o5NTNBSjZzK2Q3QzM1
            NG9Ka0FaNEVUek12UXJucGg5ajZwd28KLS0tIHpHOHV0THNBcDViMk9WYUlVMVNq
            WnM2bFBqNVREaWQ0QUVCd25KdmpjUWMKBK6UGavVSn6dx8BxDpv7yLpoawNs+qkz
            x56ddGakC6UbS4nSG4xFZYX/ZaNcrY47MsfyRJmrsPbLBa7tNljzQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-06T20:18:22Z"
    mac: ENC[AES256_GCM,data:inVfTpUWg9tdY9reLragkZZuhZiDAtFAzTy4sQfw6icBbIf13Leb0fc23yB3805sJJCRXY84gBcIlihV3WHe9d3i0KMoo2+415DwvtUb80sctWkELDAZilGNtJjkkWbrWO4YfLYtzrLDxjNJLfi0LV1kPqdpTVFxy2r0PX58HHM=,iv:usxGukhcK1XWa00rYx/yz0TW92CMFkfbAN1YwddOFBg=,tag:Cdkb5UIkutqlqrcqyXAIBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
