apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:3IrunUdVMalMJ+tMMZPsWmK0wpnJENHOW7i2kHef/1q3r6OBK/B0ddc9lDF/A5nwK25LPcc2AhN0S5iRJHTbZg==,iv:N3BPbqgSNhSeeVjbtve4WxTJoaOI2BsdbP6nzuoA1yc=,tag:spWk1F+UgsHyB+R7fBicfg==,type:str]
    secret_key: ENC[AES256_GCM,data:2cTqKkP1veJb/BKsaTlQAfbd+rOpqDc3M2J7WJ8zQfM=,iv:md8lK8GMN6XoIrQszc2+kYH+kA6fq9EfKZgJoqbxffY=,tag:0Vx4VrKsCx7A3B4wmK8myg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJd3pvUnV4TldxNlk5UmI1
            U3F5TExZWmJKc2JkVXZWcHpUNko5T3JUOEdBCnc3NnBqUDlWYjNyOEI4WXk5dGZH
            RGF3dURqRTQ3MDNHZzBCU2xmdVVtbm8KLS0tIFd0TGJlT3NnN1prTU54MDFQQlVs
            Q2IvOWRrWlpGdU80NjhWQVljTVFRN1UKZUnNSSAuZPG/n85mYEZZwryio/arUqnE
            FNBqT461itySeRmvpRokqdK+FM6aOEotNgjAEnMjtuT6LJxd0aTcEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T17:19:05Z"
    mac: ENC[AES256_GCM,data:Ix202Z1IZ7Ncoml5zk8nPmAlOlB8HwZhRwkY5HvrUai9owbsytpdnW2U35KbDHDSnHKXRqqMZ8AvzBIB2axVZKgLLUbf7+iu4ulhbyl94NO9omXbRqD+LhGH6y5IVsWGO6iTdbgx6MSEMMDX2c76oM+3oeI3g1xV6tJEfOzFQp8=,iv:wnHtVi6uKpbp8xJYoo8o1x8QbWcIbTOywQM0lT1GVbQ=,tag:sImUF5S4GXglk716MejefA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
