apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:ilvkFec1TwOMu4UHannMQjm1m+9hUWtqJ+Ksu49bpv9mJYfRzmf/TH03jrJHfHRTXmblhbsJf8+IAU6xVhKcXw==,iv:yv2GW4c+QBeo9oJO5s+iBiOBvdOBDc/Jb3A52xHsrUk=,tag:cyMMleE/zVYIV3vYi2rGrQ==,type:str]
    secret_key: ENC[AES256_GCM,data:hWpiEe8k9mTQrUctvG2krL3Nbv/kPhLGwUpyg3ksi+s=,iv:YBJhTnJ1ujEuWu0d34rXYuI6v0qrtX+36U3XMkT3mhE=,tag:e1tWWBXDYCQdWv/mEAi5uw==,type:str]
    resend_api_key: ENC[AES256_GCM,data:bj1S2aaWSeSFOQtspfOBtiYl6OE5WYNLAQ298clF2xlW2Lg0,iv:maJXgMgJlRJt9yiFVuJP2HBMcey1Jz6/0B1iB1rfJnI=,tag:A7ih8mASnhMIulivR8m6Yw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMGxZUlgzUEhhY3RYMnow
            VmFNdHBFdWtaMjFoUjZMem1OZGVxQjNhU1hRCkJTdkM3VkRES0RqQjUyZDNvS0tX
            a05GZWJVMEV0alROemVBWVNPSnlONG8KLS0tIEF1NDI2NnpuQVpDN1lLRVhMSG5J
            bkd2TllMb0VaMFBDdXRxV3VvRXlVOUkKAJkqsK5TfOZSNGAxVAGoeuRs4m17wS7D
            1mG6OGlmjh/Ij8z9sR4Va8I+aU7eYLfqWMGCvVVFWcCsZbgi7p/i5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:34:09Z"
    mac: ENC[AES256_GCM,data:xXaDE/ShzEXyqOZiZ2KDV3fggzyj61xuQ91eCSl1NY0Q7N2iKy4eTAens89TMaQktQGbsW+ekB8rG5pEQwM/vdb+4Zh9GmC3lCTBQ1IHh8FIpn9U39Vzmidxpnj0bHdXafhCm20zaO8DieFhNP0F7E0zA+ZC1Zd8tRwcMb1RTfc=,iv:1xxbmoRgD5ZFYutFlxG3AQ/vY1Dc8mOGheqijiDKVUs=,tag:T1+3eSyxGps2SLoE1pwV6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
