apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: authentik
type: Opaque
stringData:
    postgres_password: ENC[AES256_GCM,data:AnxbEwX/Kf/tB7aSDN1bPRKYJFhQv4IFAKWPErysh4+Qo13Mf2fzOMXDPMw=,iv:8463BZufwl8XkS7m/iKIso8TTEnfpJjUewhm4Z7C6F4=,tag:b67N+TArrOOVbq/a7fdqzA==,type:str]
    secret_key: ENC[AES256_GCM,data:YyjLtBkgKeBHmeIUrOc4dtq3z5ttjVmt2VGQCl174Yg=,iv:gJd2YdUz0d/1/eyvrCGATxzkR5uC0eoVVTaTfsBD6cA=,tag:xSL6p6zKEPfqjhAUufAyaQ==,type:str]
    resend_api_key: ENC[AES256_GCM,data:Gw21XVZGgEbRCL4g77dS2HlB9w7milFG8zuXFwGmlqaw0Wsv,iv:flbBTUZvmKbyVUX3r5DDHouqzN2GpN/0gzBVhexyAV8=,tag:ZVTgaN6aPKFMHKJZUDiB8g==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UmtlZ3o0MU1OcEgrY0lV
            bzRQbFpsVjFwQ3V2Qk1RejEvdTVzL0c0TWtZCjdQcVVFc2s4SkVId0NXWEd2VWUw
            cGhDcWNYVGJVMDh1ZU9mK3g0a0xmWUkKLS0tIDJQblBuRTRCaWdrdkZGUkJOUFZQ
            Rk9HZGduVVUyemdBemw4ZlhWQzhWekkKTGOAnEW4nrOmBknXQla2BtgHB1PnEq6E
            6CGoikOP5W1SlgjgrrooUh1naWUiVPcBYau4fA7kzSUBtVRJ3kTWFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T22:36:56Z"
    mac: ENC[AES256_GCM,data:4qq1E9t9OERRjwYYSQSTw3OD5W18wtxpkeuWl7wV72tqApFF7JMQnkNn1FkfHmqOqrzGBEckwQi8Sk+q6Y+73cjEDrEo+IaYjoXzXtRztq7JGRtOUAiohk0Eu/9/vSrYtZGhnJpRLUXFH9O1zX7RTDSyTHZ88B7z8RYpiim42ZY=,iv:62SUTKbjfrYt5tSKjXknpNQ9Hhs4J+QyBQmgm1h1JTI=,tag:Uqftt1mWGfPj/b6n4CCy3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
