apiVersion: v1
kind: Secret
metadata:
    name: postgres-main-superuser
    namespace: authentik
stringData:
    password: ENC[AES256_GCM,data:x7wNIIjo+gvQC2NaQsgST7ZRBJOuGSXvT8Jyigv+TsM=,iv:tIT0tmyrJzqy9rsQLKQrx5GWTJf08Bzt9fo3gUk1hLs=,tag:Txc/uS+OGHNt+m/hScm5CA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bHpOdldCd2NKdUJZOVdR
            VldGU2dWSFhaNUpYbDRaelRWWTVoR0dnTTFvCkxndm5LdDh6L3pvbk0rSzR4QmNZ
            eVdEQjFUeE1waFRwcHpXdURGTzBYRHMKLS0tIGdNWU9UdEQ1T3JoWDV3MnVWNVJ6
            YTJZWGpNTTIyYi9xOTFPUG1pN255aHMKyuC+rK9hNwOOwZybvZl+xCSY2mAe5F5E
            3D0iuQPgBqN22Jm7g6IqmCSX4pq8U92qUqFQWzW+YA+MNjRXhoWfcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:34:09Z"
    mac: ENC[AES256_GCM,data:se0nZC2eHU6o+MohnhB7MnBB00iR80RfQCp6LVlArYcnNVqzb6ob/qVu3M3ZoMlSdNgdUgpI8uASMTKcSOwyVB+iA6sNELjHtExjFdFZOvE0sDqunT305OEULoh1rM6zmoPjegkoX20suN1hf654QIY4tcqUaKNJnEFwhoxOe2I=,iv:AEpqC6KDjVniw8bBDjoWHsmjZbAz6mmGA0y6PPgXWHQ=,tag:8GXjy+0T0Ji8XxO330gawA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
