apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:0REFwi1apB+v5l2AYRGtJe2U6/X4QhlDiuvdcCFiNrnmIqbxnasEzcBEkWE=,iv:yS9q3djhSOn8bIX62qm2mH7fU4wtBe0eF9PjCDkJUtk=,tag:U7VLo2eKUdaC9ibEb1W/6Q==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZERwKytVYlo3aWhZaGlk
            S1A1Mjd6clVuL0k4NVYvOXUvb0RiYUhJckVJCk43K0JMZ1BwRTAvejVVRTFnK1JD
            YklZRENNaFFvQjFFZ3NzZU4vN0gwckEKLS0tIGdObi90MHpud0hnUE9BdlBFN0hZ
            cGxPR2ltWUxYejlVaDBzK1paNDVveTgK8jWh/pIbT2uMI3jKjpK/2e6QYcfWq0Nx
            7S3m0iMSsv/NCYfa3q1ChhgIZaS2EFkk6uquorbWavwck2nGFnPocQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:34:09Z"
    mac: ENC[AES256_GCM,data:eLoPQTc7kWtz9roq03Xx+GU7vYfa90VQOtEYd3J+2BYOWwSTS5qBrb0jrBn1mmPFmPHh2cZvzzaE0RaDkLI4cjF22C5TGiy6dk3/nG0Lw89spMLL4+GHQ4XYPpQHDpLzDlLhqtL13SkfFs5uQb0slrBENiJdkYT4TXdU/Dt17JM=,iv:6dHZJZ1Noo7JXAtW3APm9YFJi5/1hDBqyhze1x9fazk=,tag:iQ7Mwn+WeC+TdwKwnXH4LQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
