apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:k0ZsIdcfuXFc/k+nm3T6sGoxWejsts2beGtmKp2/usV1p6sKC6PsnpIfu+g=,iv:SHtyR73/leuWludmuKFzNAzYiL7GlsChXRS/nrWbS8E=,tag:oqGfa4clHwkeeNeCiVDexw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSN1ZTRGVJVlVTRTNLMk85
            a01OTTZuc2RXNnJQV0tZRGJpV3FQVnovNnd3ClN0NmRteG5OVDdlVDdVL0Q2U1ow
            RnZxT2ZPdy9ocW1rOGM4UWRLU1VibDAKLS0tIDZoWitCclVoak1TQ1ZpakYxbktQ
            bW5CSXpVUnlLUkIraWR6ckVHaFZzckEK02EWu0fUkeG5ontrTIx3CZ8/8oNb4DUo
            nQbPUTr45tmCzBYiVywhFxbT4T+tXxqZjneLuHwb7/y9T08cgVfwGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T18:04:40Z"
    mac: ENC[AES256_GCM,data:c9yjaxsDMi6sbSSwBtochmcxHEjhSzT9lgeRKDsFf1MZrSrf12FwDUbulLop5i61k7e2BFlZdVlCax9fSAOuJgs0YysX1IgGa0z/6Vi7Bag6rp2FIkKeSeld3b39hdPQCGiQ311r5lQ/LsEmmWjTAuJay01WSnQJMK6jdW5djuA=,iv:8s8i642g02RmQx8PtLcOJtRQ8VAAI4RUpqPPRUlAG/E=,tag:IcCw4D9pjHgPghC66oW1Dw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
