apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:MOTIB+w6YSG2xNZFIy8p7yLFc+fvc5JRPux7khIUi8hLWsMpQGt0BYgC314=,iv:DlWPXOMX/4xvjmstOEb4rtNPYpW5j4USQQRrvGjm8Qc=,tag:nTlGYuGzf+Sym0fkNzG3CA==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:D74sAoiXPUNQBNUMKiZzqpi97DI96AszVu31C7TRNT4OfrPgGS+KY7b89BXT9Sa1jLwIXThkXu3jWeyOsqg1cg==,iv:JoW+UoZiejlj/cw4JRbi3EY9cpxYsopycNCZSEee1dg=,tag:LAW2tHuhf53Ikq+pwAV02g==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMTBoVG9nQkVSVmFQWmZl
            cTh4SlEyWlduQkpQSW5oNE9JUk9sMC9hY2g4CkRiTE1ObjA2cEZ3K25aMTJBbWdj
            bEZ5dk8vVWUxQkNSdUdlTUNUUzJWUmMKLS0tIGh1YTVVSjlPNC9hTXNKQVpndjB2
            K2xzUUJPTEpheThaWFp3TXZlWlowR1UKxCOANhs5NjDT8xfCRvjYZtCTQHXxBw5X
            PWI/n3PfrU2ptvWEv5mfbYQ5QRBgiv1NFdnl7DQcqT7x1yXF61ulaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:35:39Z"
    mac: ENC[AES256_GCM,data:fty2XMwHefGBbu8je54lhWZFTylNON2m9XpcJXzBkQyS1iUDAGS3pVJ6qZkrfNdbOgldCDhaYc5M+B2daieEBdwx0ztjSleabY4wQejAMOUqL7F5ESG3U7NSE/sb2g44smN+MKhZSlAQSMWnISXfs63CoHTIZIozBewtb+1woo0=,iv:RwFGD5YPQjoTuECMf5/4inHKZk3lw5va1xq8aKwdgPY=,tag:bu/OiRUD3P9h8BPExci6tw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
