apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:t6qm4PZK3Ano9NJWnWZexG5tiY0PRMXStk+mASfcoBPKosbbrKrB7IStq04=,iv:z6VVjiMW6SsWp+yo/pWyMld3FQRxkn+ABw3A4MCD6kA=,tag:9jEprxqGzIdRcWTfaaeD/g==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK3E0L2xuMTNySStYK1VG
            cFcvVnhxSGQxVmlhRDd3QjFRajVkeE4zeWxrCk5YeStIb3FLRTlTSWwxVW0wSDNW
            VnJZZmhuRS9zWmpyQURmeXJjMGdlQjgKLS0tIFl3MnY1QVJXVzAzSll1a3pxejM2
            WHFxem1qUU9kM3ViQUo4V3Q1SUFrWm8KCxK/UoCoMWIxPJhK+C7IgSplKfqHXoFC
            1zq/afWUhbZ6gdOVizTlFnmA6ADqxMM50QWqs8kQo453LCcQoMheHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:25:09Z"
    mac: ENC[AES256_GCM,data:+38pSTinqzJsSPnVAm0OEqLqBNeXpERmE1XVsl6FHPN8k7huQ9ro2+2VOrVZArF47/EuObMoNwEh91odJBRLH0Ihjnv5o3Djtxc8l3IjDEMbEd6tNilwfcHyIkrhFXMdEwJ4VoeHlNks2S3M/RDcy3uQx2u9qSAr7Totf57vSmA=,iv:hn4P9qMOumcoxH4ENprtvoo9X1YE7pwwbUdfaUEneHQ=,tag:nPmKSIuEBOp+xYG9YOskVg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
