apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:CPwF0i1HrjmQ+2KiEsNMPnZt1cR0pt5Ebe182y48+0jEP85MUIG7HSYHlQc=,iv:Vh6MfKY+8u3pTgfPEVJji3tg2l/NrRvyKU81bmCsZ48=,tag:nMlPc9zqjd2cAoJTOBYWDQ==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:VoA1E4POJnLdz2CJbL8vpcjszsq41yBgkRjZ5RGnNkzVt5YGRY099zU/+svejnQ8Us5KphyhBHp2TjSgt2I6cA==,iv:koSP2/1RKhufTf9nbooGS7xkRGOkVZHSGYNTYQ2Vqv8=,tag:we3/993IBQWJ4vIukrEDvA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEUUQ2ZGdGN1FXa0VlYWVT
            M05ENWRSYW5Wek15aHFXa29aeWNGdWt1K2pNClZpUXdXL0xGbExGZURLeXVnTERu
            djZrZUZ0cXhIMG9RTkc3OGpDeXhFSk0KLS0tIDdUNjY5WWszeUk3c3BIOHRLNGJX
            RmlPMFVCdmZmNWJJdHRqVzN5akkzcU0KdKtiUWLkPPWFMfbTfwIdKMJ6JnIfw29A
            tUb2Su+SV8gMNUd6BsY5Q0gbmYG31eUXszD38vZzXl4AUiepXiFebw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:43:18Z"
    mac: ENC[AES256_GCM,data:tws2bjXZzldBK03zfILf3FkAMWmvs3b7BKZ2FMXt3GoVkzbfEGbaj/MIhdDg+7kWJlxGIIoTMmz4twLt9cawUq/2L/uVrTTlwu+yByAZp1VXCCRgbn3pQ+FtpJvjQccVcyCGam3J5xUUHdtcaV2hzVsd2M6tqoyQGwuEts0ePg0=,iv:l9omCcVGYREmLw2pBjoAPtoFVB+u+AuFZ6OQpKmBpQ8=,tag:S0fC6AJelizyZVPc+Rqh6Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
