apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:QONJDxolEYBuFKkPtcqu6NJCEfFEFqruxRDq7rX4OBg=,iv:5H7d2zkrTwz/CZ420F++dKNY7afIyZ/GYJg4pVd9kXw=,tag:7BylBXRFhG74QvzepNoCzg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBNEtVdkdhSzBXQmx0VU44
            T2d1NUZzdTZXWnRtSVpRcFU2bGR6TDlQMlVJCm83NGg4WnpRM1pHQVpDNWpFaTBP
            Qk1sL0l2cEZwOTR1NG16SnluV21ucTgKLS0tIDRQNXpwcWx4Qmc0TzB5bE12SXh5
            dTR3akRFUEluZjI3SEkvMUxkUFdheFkKUOlo54mH28mA8DLg8mzp7xezd/4mp28i
            FUxbtvAPcucHPQvhDNjMTw1/pNvfHxKhOw2ev8ePfeE/UuS9eghsLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T17:14:12Z"
    mac: ENC[AES256_GCM,data:Kp0pZziByHA8F+hFCPv0IEGcolnTiwR1MamYxvdhA/NjhuclqjhCoBuJSyGF0u0ZPhvwQBAs5bf/tvENz4xQzKw6lXwwsn3kkhALyLS4+3QWbCbISnc1FMqATEOK8eeYUrWtEh1mGaywqotXwtxmgFuOYbCQv3oV+8bVZfqH3Ek=,iv:thm1Hir95Z7/jxI3hhDFCLobrlQ/mwdT920lGyLa3xw=,tag:XbL95cao0SkGP9OBDOe15w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
