apiVersion: v1
kind: Secret
metadata:
    name: n8n-secret
    namespace: n8n
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:kxKb898NpIuMt78g1YbfJDbgGx+e6bt4wDj9TvxxdT40GAxVbTLNF6nD6og=,iv:nEx5cMRn83+c/BaOYyKPpnkq1sAPLAvTZtXY7DSS490=,tag:Ay/WkaiX1T9Eyh13ypVHlA==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:+SBgms2qtVVC9UWd6aWaDMv0E1SLWMr0tNQQjsGjR6KxFGJ9pKkgI/P7mwdkTcvqFUTfabjSyymfL7eqLDvwWw==,iv:l+iSLXqOavUsmypHN4TuTHufR3U2CWNhLTBq/orYQHs=,tag:K+gQPoeylVVkay6lXl7SxA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWMExFcG5TenVQVS9SbEox
            U2NLQzRYNEtJbmw4VEdMU0poMHFFTlZSN0hJCkI4U2FWTjNzd0R4U29yditwZUNr
            N0k3NldVdG5DUDBLUFZiUVgyZGswT2sKLS0tIFV3M3lEdXRlQmxicFkzMUVQVGFt
            RHJzbllkK3dLSFc1LzhFZnZUWHNqMTgKBSiP8fqDloSP0Dyy2XniVfIicJDDqsd3
            yB6RqJ76DaRCtjODDIR8sHoSg4Wuf+gj1ThecjBR/DWdff+mWRpQ5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T22:36:56Z"
    mac: ENC[AES256_GCM,data:wWFVyTOO+x8ckA7uUWv2iSY/zzbJO0mS110VJS76hO3/sh97Itay6oVcTWsYo2qLLbTG38f6kE57ly+AfaGP/KbIVYv/K+Bilwn+K2qpdaeFiAfrwRtWE/M6q2kl6hqr5s+VGjZvObFsyC+xuvZBjEooTx7E0l6R0PnbIX3iN5Y=,iv:5em9wFBEK8W8w30xVljsEdvwJz1InLp38SrHCsgtmS8=,tag:kb0F6DxsjfGVRXhNwVSQDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
