apiVersion: v1
kind: Secret
metadata:
    name: postgres-main-superuser
    namespace: n8n
stringData:
    password: ENC[AES256_GCM,data:TuWl9i7RtaOToNchjFjo229d4nEwtCe5Grm+o4nG+54=,iv:76xSaB3JBCot8/kaeHXqTE8skPYWTCnWGMzVc7RZuvg=,tag:88ai21WPKbNtnEMLhuvwhA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVDA3VHg2R0tVVER6WitP
            ZURrM28zTG1mdVRLK1J0NWVDSm5kdUNkdFFjClhVVGJyTjVkRjhyV09ieDQzcCty
            ZmdzUHA3MEhGemlGeU1ST0dQaG4wQzgKLS0tIGhEVlg2L09lMHA2dE1VbUVIMVJC
            dDlpbW4vVWhZWHZSa2VVY0lyd0pPaDQKVBL9QH+M2rR0SrNhvbObDdFqwHB5KJ/L
            UCp3MOoo2pdjoqjgI3aiq8+DzS61aVdyrb1zJa8yMXNVQqhko4jwCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:34:09Z"
    mac: ENC[AES256_GCM,data:E+pD55wWLiI6bk1ytqOQl0nGSOKkWpjBNq+F6HvcdQdyDsmKy1YaNlauGCfwzr+tXMfpr32YND4dSqaRkbLzpKDWeASsIRAgPdscMQFMbsclgYxiXYUYIN6VrydhYpUhRv0E4oh5L7jKG83s2rwTpz5Uj2dBOLKaafg96OkeFSk=,iv:Ca9m2XVIgjLmX4lTZ84/9M0gGnJphrWk0uLoIx8cRN4=,tag:7SX77B1/G0PoBryhNV49xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
