apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:Dc9Nvs9Bp7Q26VFuFCCJioXg3/yvvcG/80vnR+ba0GuKt8cRJQ49bA==,iv:0jhxKGR1nCcwQbRwjVG9Dmx70DY+ClZ7+SECneqsefM=,tag:8+qx5VoBNMkdxUZGlUPckg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSWRkaFdrZk56Y3RjeURT
            ZFdFNHhjRE5TaW5qZEp6L05uNjNhTFNQRmljCi8xaFBoWWVvMGwzSDVtTXRSSFFW
            N2NmU1hjdndBb3hRUHR3VldUZk81anMKLS0tIHNoWXQwQStwR0pXenBrOWZvb005
            UElVS2VLZjVBVHNFaHFORFFjSncxQmcKh6VLKvFdyNe5bdegXPLp7RMffmjIdu7/
            JHhZQOqmqh4yXTc2ooKIWgCWu1734EMxdn7ND/DpoOVAjrhJsEU+KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:35:39Z"
    mac: ENC[AES256_GCM,data:35wk20Vn5l+GRiGtbq+LYRSGFrOAgwqk7cYa1c3o+rDSnzKjNWBxTTnMbw5HDEso4A5AxwGHoNvqCpEhvtC2CgBBkmzhNfcgsDHm2bzcqrSd+WRdJfce6NBRD5tYFjhrQupaO+7xOZuCyNeTxKggHoh0uJXcVNfewezuEWtAxGs=,iv:x59f1iSlZK6gMgCAlewbJvMmm5e5toF1BCUw5/NsE2Q=,tag:zTpG5RSLezgvJI0oAKmnPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
