apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:qT3ZAP0IRcvronpqrI0TSI9WkD5CiQjEyjCnDDzcehBEIj79MQ9Nng==,iv:J4hN8aL5L0SvKBt7kAjVadhVPndYDh8zfldm8fYUNHQ=,tag:LMtfelnN48nX/5kopeZgfw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3S1BiV3I4ZE9wNFU1NGlI
            N1ROYUFiaitGMERzUklheGUycWg0T0x1c1E0CkgvdnAzL3B1NGRMWm81NU42c1Qz
            ZzdkV05ZTThSS2RvM1FkQU1wZWZ4RmcKLS0tIElHWXRGQ0k2Y016d0FhM25DdHVJ
            c0ZsT0FqaEVObW9sQjlRbUZxWnlVMGMKWqiX/a/hC6daI1cQojG1cv+94UblGzfG
            aqYQQaLhuSxT45dw0NgwWZDqxebP0UUcxp7+JMRfzIQ11a/5J6V/jQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:43:18Z"
    mac: ENC[AES256_GCM,data:ysQsn7d/gtRsTPvM+GPiTurMb2+qjvhdG/auG9FXQ0/dMxSrzx9/hSADRibWLs9EArlsdI1zIe0UldTgze9+x9pNdVMJoDcQsersZU5lYkcWdcIa7E0vgReoqZ/S0IywoId+87lIekn6pS/6O97rOZW5IYwgh0w6xqhk7AAbe8U=,iv:7JZQ7wuDkp54oJjRtreMNij74lUW0Kh7yrDrJwScuSk=,tag:fBBjvGNYdoSBD1oI0HKz9Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
