apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:emkapQJ8k3+2OBjCzUnOV7qGDhvvLreI6MbhyDeFk5bOa3dm3VjUcw==,iv:7wmw+hpOZKLqPbvi46ydPEwE5KjokC1rxnpFcJS+QaM=,tag:jeiUbYYQ90O0JrDvRcDUbQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoRmRiSm9yNUdFL3AwQ0Jq
            VnUyTUNQUWpGRGhrZGIxazFmSXlzL2pFQ2lRCjQ1aTdlTmJpSW9wVno2SEVSdWJ3
            NTFseXhMQVA5SGFCajFBY2x6ZnVXZVUKLS0tIE8yakplcUUzNGRiVTE1eDhkSFRT
            UEl0WGxGVmE4L3lnV1hKdE9sakVDTnMKl194Ye2sSv8X9jZ/XwpLg3mHD3Z89Kw4
            +Zva1hr8EQJqRf9I81XRomjDCQakP9lQ0Z3bPQXkcYISuHilJXk+Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T22:36:56Z"
    mac: ENC[AES256_GCM,data:b+EdVzDgOTww6GIbbDLXz3Ruokqg/GfVSq5Nqjmd9IlZOVLe9JCmqVKhwGR2gqAE1VHF8ueUWmWvPEn9IL/eRc04Qr1j/Hkp8fYinzqS364Np3jXwnhltNtIAhnrrt9XYdqF9xO4i914z473e4kGsR6GGjLF8jPrKbgP+/nsZiI=,iv:9jdSohA1asDZRC1R7qpqlyRNF072MrvajaV8ut1F6RM=,tag:1vSoXNzuQ6bTmHtfurxWug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
