apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:O5+EeCze5bODuKdA4Wq3OlMJroPlCSozEwKzRRuAZXXac7TUQ8i2OQ==,iv:2+en0b/j1SJLikl44tNx2Ea8z4Fu0mHx/ZoLrB2BTiY=,tag:2RqDOZigC10pcgYCuvak5A==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUck9SUFlwUUc2OHdvQ3B1
            aVdjZGpKTSt4OUhMZm84ckZkTHhoMnFzZFQwCkU5ZWIyVzBMODNlTytDVzc3c1FN
            RG1aV0lSa0cvb1o0NnQwcEU0VnZTS28KLS0tIG5RUlE3UHQ3dWhxSGpIZnFhVjZq
            ZEpydng5a2FPWlFDemdWUDVWTUhBSDgK9q4jGqrUA3WdYZ/2Y4uTGU9GFZDj/PXh
            AbcbFB0oZcbORIlFv9fjirLow9/TMRbIVBfWf4w6xp7zKO+njBgqsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T18:04:39Z"
    mac: ENC[AES256_GCM,data:9Rl62Y/X79fslGpkhFyzD8Z2Z7mEJDk0RDkXEmVrSnVMpZkeYApgjs3qagMs+5Bi0vKLAvB3oXxruD9Dirubz9rE5dLCQMKBItin26xbI+zJ7tm0vh9jUA7j2hxh49BiDp3Nx5VXZ3Hdd4G0mf2HZTGB+YywIGVRZV3G/l0we+c=,iv:9x3nM81GqnGwh7DL0Ye87AkwfiroAybppW2zM6xUOMQ=,tag:ne+N7yYmMcKamS9VZkc24w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
