apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:JUH0oZj87Jrz7oXundkWBcW7AKLw7JjE5EWk3Jb8x1KnrOJY3DaB9KFg46U=,iv:A2EoEMw4j4yeViqmQy9Z746mTakmmaKNM1dMJZd+f+4=,tag:chU2BL4esFp00rfnnwAHIQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBML2lBTFRqbC9Ua25MVzdU
            aFVxT3BlYUMvbE96aUFoY0FXU0JzZUNMQkZFCjBlVUhiZk9hVHdOcnhMak55dTN5
            cFlLQXIvQWUrSzRidGlqVlY5WGIxTzgKLS0tIGcyRHJKcWRTcHhETlh2QW1Qd1N3
            MlVSNUhyeDZCZHNRWXplMTNuSDVWV3MKpQ3INBsjgwc5hSuFACqKKo0JE/Kcvq4X
            NkX2OeiQDV2c1GpYHYXl5lcHwYpfbXY0VH+4Vz1YQx86f7VYz94k7g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T22:36:56Z"
    mac: ENC[AES256_GCM,data:FCzCv1wTyUQiArEVUgWOy+UThSn/46CKyIdGLHIbPsrffKAwwYDUOv0GJVM2YI5TYNtv6fJjZuIR5hsMscd0s/yYjA/vVaZaXd0+uD4oG7RsZa1dX+DQYhnzbtS+N8p43suRfIyHg1zYqWVI7XUEFM83KSmXGjzC4LI/tDYHKqM=,iv:LLERGyqFGqqvrqmhJrBc8LRef8ws9myUV/BKoqyVS08=,tag:ta5mSjWp0YInava9/hW4DQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
