apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: database
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:IwnmE+bq5H32,iv:lt7ce/CZskcxO0xTrOABbcOF8Wluld5phRGFD7dKzwU=,tag:3nG+JC+qPEw0BQSSDXQKFg==,type:str]
    password: ENC[AES256_GCM,data:7fiBc+w5Rkg+5MrHacCTdOK6F3JSsjH++isvl2glmfeMgJZ0ON6J4OuBvpwylPTQYDn7VPayCzcRa2TghPIutA==,iv:ZipOuMMb4YHpUyjhk2yON1vX/z1QnJ2ji3pi1w+96uc=,tag:53oo+J0IbTBMQpBZBB9JbA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoLy90Q2lXV0c4YkF5VG13
            UG54RUMwVktmTHpWN3poUnk3cHBhQTFBQ0JrClVVV0FCclBPZ0NSekoxN2JscGtR
            RnBCOU42L0RSZXNWeHFrd3VaZ3A0Z3cKLS0tIG9KaHdQTW93RlRHSXR3VVN0NCt0
            eVBwZFI4cm5vVkJrQ0JTcDV3ejB5N3cK3g0blvIpo6OeVIKhbhNZzEs99H7QXELM
            3O2m3G1Da1PObk8/PHHjB5HnUe34Es0DN5PRc85YZNDrjCbwRLCZ+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T17:14:08Z"
    mac: ENC[AES256_GCM,data:SHG3g5DR7lQlkfr5BHgVuy/BvIKMQCceDVqlv5T919Ar+LNg5Ay25/x87cYgLRFDn9wWPeUVRcksF+96fiy8gzl5A2tl+S89Puev8GN9t9A6TMyTVGWZr+ZBHkt6jIeXsymWKxaK3X4CxM4edlf+uksIyuFl/3BHGpcvM2BBl0s=,iv:A7BDYuxHsXZD8oQbs7y/tALr1y1w1lOqMpQH/vmRe2Q=,tag:AzEIa6bG/r2zbVjBwGqEUQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
