apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:kRek2fs84OgOrk+eA2fyxvz5SQZvGnahrx+kBjOa0DhWTX7bDYLdzxwwdDY=,iv:GXOTpVZ96knQdXno9pctkNm4cEpArjji5gU0mHWGTmk=,tag:uPK0TROfZ1w95ZQDgT+QUw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QVhnWkRsWHRJSmxzSEM1
            RVY1T3dTSmRuY2dTdmlWRnluNjJMQ095VUQ4Cmg0WVBuU0lQL2FLY3Z1a1kyaXdE
            b1dSTmRkUHdXQjE2TVAyNEVpdmZ2ZkEKLS0tIE80bTFXRHVUdkxzWTZkbzlEdjZX
            WDNUb1FnUjBzMHlrMmxTU29BMTl0ek0K05++aF6eFdkmF8Vf56gBcyi87R4B/fiG
            Z1E3cebyVHUjByodrly0fbi0eABZ3VREfhpN8GsUeYRa57PXyf5vqg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:35:39Z"
    mac: ENC[AES256_GCM,data:EQ4IqvyVmFstXbX3zI0M5vsUEk7Crag8YHmtFQuEVh0INzLvV6CJ1LE3H6QbX9AxFQo5BlYA0W8ZyIgy46U5o7ePcw3/xU2nklFDj1/3LLyYqI73BWgcdTSrBdOzNkK6+EQCaGkqRE276Us4fNz3fxoE2/Pfb252406/PwRNXKQ=,iv:7QdBaUCf6xoU7u5oHSiD4TrYt7Of243+WDinwBwLG1Q=,tag:2GvpEq1YijJ152YPBGf/ug==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
