apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:mojJcyUU09YBu4cHT/MuDR7zLQLG5rO3qu5HsLKLt/hgutlCJiPPCcuU8a0=,iv:a5q9iWoTy9xeI1CHpaWjjcwmk3dQ9s9j5p1aVU/Vcuw=,tag:aLUd3SqN7LMKqtFYtJxjlQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQ3Y4dWNVL1FsMjlQNmZZ
            aW5KNGFzRmkvQWdraTl0T2cvUnlWcXg3YW1vClA0UFBGaWE2Z09ac3F1MW1WYkhV
            ZHZNT2NkQXhwMjlINlpaV2FiWGVWUFUKLS0tIE9SWGUxSEM3aThBQ3lMMmdiaXlx
            dEpPWENkUTY5Z1dZdzhyZ3R2VzFOTHcKb/DEOkjDURw6A09CWdbyKBQOr5Xsw1wP
            l9Ol12VpR1+lCjp8e3Ad5quyxWHAjniWADo7UsJmD1/bukpujJzaqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T18:04:39Z"
    mac: ENC[AES256_GCM,data:AD6uzxGCD8Q/YbNQF/kIo5GjeoTetgjMfdi/VzuBQCu1LPt8C77+Zai4uGMTiALUxk/tJZyYP5gP0jrpJzI/7HTs5YBRINHrfkUgu/sQkS8Cp8492g0BQQfO9bZKc2d1I4L/2WDEUWLOQqBIO5/Q6elbHs+udDslRR86TaLxgcw=,iv:MgfA4yi+XIMTttmfb3bxHI8VMrsmQCR5G7Ejlpyti/o=,tag:7F7oQQpXbF6G5uwmb7Ss2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
