apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:mMApRhCABhnX6/SOgOFYcIakFOTg7DobCVu6z8y7ZRz1gcLreJz6ISONerk=,iv:RwvrK+XGC2BRHAw9hEwXsJODGgQh/8oK3Nady4Fp8D0=,tag:F0sqetDZ5lPwIVI+eFxuxA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRm1JWjNXazRmSjZidmxP
            NlNheHVKMktmUXkranRXa0psZ2hwZkhzMjJnCnVxTWpDSkVJZ3Q3WXE1SW43VXJN
            cGY3QzJCSGRsSnFpNExGMXJsb1lTVjAKLS0tIE1ybjFtaVNVc1p0QzlCSUZ0dHdw
            MHQrYjhwbW5PTUE5YzVjRXN4cHF2TkUKAMzQovY+cadTA6eA98HzSuk+T7H4ytY7
            DcDQBL4x1Gd/9e6zNPu55robCyU6zxBytHxToZKYYtTJbn3RInzrcw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:43:18Z"
    mac: ENC[AES256_GCM,data:+lZI3lVV7rWUn7QDZsftR1HYltTss+rC1/iWxYpf1HrGktu1Y8ijeT20Vd0ayMOEJVkMlmssJG9lMhqCiWRNv8Mrk/7oSKEnBgNQb/24o0o7Lc8r8vAN3A1gtIBsFJzZlzKo7CYhCBdnXDoRd+wu0pVn7GDyuTtzWy+KWUedgH4=,iv:ONSmkfc4+QGAW0N2gZP1LbzrvC2BLRjd7cbS/b+SPCs=,tag:4EWtXX+DCk/HzUByUOjxMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
