apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: authentik
  namespace: database
spec:
  name: authentik
  owner: authentik
  cluster:
    name: postgres-main
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: n8n
  namespace: database
spec:
  name: n8n
  owner: n8n
  cluster:
    name: postgres-main
