apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - authentik-db-secret.enc.yaml
  - n8n-db-secret.enc.yaml
  - postgres-main-superuser.enc.yaml
  - postgres-main.yaml
