apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secret
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:SQOGfJzdZ8RLQa8gjUyTEBeoW3QBtMrTm0/EcQou2yX1GSN0rfDxyv74Cv4=,iv:EtLty7eZxNv3gvwzrWzchOM38o285q8UXax2WxGrOzY=,tag:ZjC9WuVHWuLEfo0rjTAQ0A==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFcFFGNm1rU0M5QmI5ZFBv
            c2EydnpacDZBVXc1MW96OS9PMDV6V21Qa0ZzCjQ2cmh4Qy9NZnZHakNRNm9VS0FX
            K3A3cU9UczdpMzRVSWJlWHVwUlFDd28KLS0tIEU3QVlQM2ppaG0yQWVncDNQUmVJ
            azBPY1RCNURmaWRUS0FZalcwQjNhRDAKXuEB7WjBTU/AvwEa4vKJVmvf5x3Y02/a
            qz6OJ9J76gARA0QKfE72Fj86h+IZY4XFGrruEEWYae6gbLgsllMFHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:43:18Z"
    mac: ENC[AES256_GCM,data:zKL6bNpgIE7YaOSX8KgMP0vaJ2+ij6tb3o0fogV/C3iXk9iLlWdyqHADBWIzM4u+twzYeoRQchWHLqnveSAazwwIr0cTYHX6s7fzwxYjYYVNsJBQUUHW1MJUEI+j9Y7a8zCVEsIaqTp5tJptNy9H445ozZOiksgS0ywMdN+Ergs=,iv:m9DshYeyuPZC41+CpL4D4j6Sztya/Jkv4Uh1dradA3s=,tag:AWDOL4Qm6aa2lycugqlwzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
