apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secret
    namespace: database
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:NJJe,iv:9NlvjYMly7mbRG1c5TaO0JUknrEBDGzykoFi1RaOXKE=,tag:GWCHDCNuoX1SKi2v/4JmLA==,type:str]
    password: ENC[AES256_GCM,data:EJs93tARlDTuSx0dr/EPWbHSLFJ6rA9W4P/BMDG8l4I=,iv:bWrqlyureriNOeuQzLZ1gZ16Rq71PKU3Px3qoNP4Meg=,tag:JKfCAUjd76NE1PyaHf1xYA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhU1FpQTlUaTlrZURLMEZy
            SVlOQ3pIWlVqK05OZWpGb0ZNQnl0bmtPWkZZCmRUSGZ5R3JMU0wyaTUyTDZJZnNu
            cGxWdFprNWRvUHFNYldXaWU0NnAyaTAKLS0tIGUrOWF0YVV1WTZ2dnFlN3VpY1cy
            YU1JazZQRDlMb2g4VGNQMnQ4WjZBbHMK0vKoq/IU6MgD3jLSyrC+OWflZlz9/0Cy
            i8UcskfdP0LJvvqb8NCVfB+52UwlbZi16vM37GOhCTCZ2nCEJFIeBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T17:14:10Z"
    mac: ENC[AES256_GCM,data:omrv28LQc9o6kevNvyIkIU2Coow9FfJdbYOekg7FTO7y/aoVcMlSA72cmFJUdXgtCUUqBmZUrCbYMZagVEAw86n2gulDb/E9iXbjOTn/0B081o+DYSa/1/8v87KbV1xuHdPFpdvmWyIpUmeES9gKT9bwSOE2IJehnV51+Fto0lk=,iv:pRKyRQ0XTUeQuBFHkS0VMas+6QH/+lPKLy4OkPFjM/8=,tag:wF9+DujLF3mQTHh5tshjjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
