apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secret
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:WyezG10npGwVW7zQNaBWVpZrFjdDWZmvVycB/wPUn/Rk+pc/99dVIjq/phg=,iv:NNvotogq10uqYcEPU7rg1gVp7Iy+Hm4fnVd7H6e3z6E=,tag:MV1mS/0t5lYAlvc95X/AHQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZUJjalFnSlZUSDRDVmsy
            Ni9xSWFKUDhCOGdCWDhVMmg0NG9uenZzdm5ZCjNySkRvK01VVVZ4SzV6RHRweDB6
            akpUaXdFNHpsV0JyZGRUcEJvKzZQUFUKLS0tIEY1eE9HaU85SFZleGw4bVRmdnhQ
            b05CTWxXMDIrZVcrMVNqTjFOK041Y2sKyRr5315Ax8MI4MB9Ai/2k8NkxGh7I8mY
            PuR8zUSi2MqYnPXZcvr0gKuVez2xVEnTq+L0aNgT87mXdndfwbVjNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T18:04:40Z"
    mac: ENC[AES256_GCM,data:4ZVBB1QYJsyNZT8u9uIVHN06nBsenSYslVamdyg4g17MM2qTov7ikzun0fY4hpKfUXBlcEyYgJuVY1glMS0f0flG/gauy/Aplg7smguUmT7J72GYnVxZt1nFFnVb1xpSkKh0Ulg6f4j/RjEw+anrp5hXEcgzMZ0RNBqCqfiaYYo=,iv:GBztoHUKAKCsj3vFw8MuNXVaB2Qa3W/zqV8XVavpffE=,tag:F2TfkipZub3jLOBflS/+9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
