apiVersion: v1
kind: Secret
metadata:
    name: n8n-db-secret
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:Kn6U6JzrmGINehnhWdbtZ3dxj0fHy3qUNreH/MhdlTw7jBoL0l57arW10uw=,iv:yujlGEsnJhkiQa26Y2ue6QG0SSPglwELHbiwWFnTwn0=,tag:AUmf094/jB4C5p20WRLZKQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSUlMSjZZb3pvVnhFQThW
            L2FmS1B6WjVNejhNVk83QXZWMW1PcDJRVTFrCldFM0hZOUFSQ1Y1Wk1wd2RZOUNL
            ZFRqdzFoZ1UrYU5nYUtSS2NiRHlhRlUKLS0tIDJXZ3ZEREhybW1qVkhwOE1sbHB5
            aXRXMzhHU0pQck94QjE0SnNFRU04Zk0KqgO7H9zVkcj7i+4zuU3VujvcGx3PLa/T
            lBY9VZcjNe0D9coFHx0T9ypewB6xH8b87LQAIldiO9z6VxKK8iqPPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T22:36:56Z"
    mac: ENC[AES256_GCM,data:2BFtBsaT+8lkFik4OaUH0Sc7Uso7ZvB1h2Y26g/sw3FmD6Frzjq0B4r91eON84AaOMJbGRcBwUnZEpq+4b9QfCHbm/DCuJmI8up/w/834BFUIB3tuIBICFfhNVm+tXIpdpdduWR/ozrs1raLsRgffIxtkXFR//vsQGqyghFizMQ=,iv:nGaanpsakUOyGaVtGwwXeMeuC/A/duUY/UvfwncL/H0=,tag:6lJ2HO/kJjCRMPhIqhthKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
