apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: database
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:s9DvOd8ffzmxX1V4JVfs/7shgc0xgbHpk9aSiFB03OcHokpMG9Qvw1lksGyWUPtyUKfCM7K2+pjObvB4BoJLyQ==,iv:SiXRiJ9XiOUfohNBK+jcK0g6/2g7AuhO4i3gw31P5r0=,tag:ayk5WBweWD8hamxHTgT2xw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwU1dYVzZpKytDWlJoK0Mx
            MlYwRmxIUjZaWlNwdFVkQmNpWmFReXV4SnhnCmZwd2I0K05vM1ZqNDQxRjd1MGJ2
            WEE5UVIwbXRqYXFFQXJ3dE10K2FlZXMKLS0tIE9xVFhQUkhwK1V6alkzbG1Rckl2
            SzFRSTRVUXgzTGlYZ0V3NFRnL1NPck0KBiF++8H36sYtJ0wUlwYBU0ye71ZFMuGI
            OdVyaFYftjgXnTH33u9AAr3/T6syTMg38ncS4Jzs/ogvDqdOoLKW2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T16:31:38Z"
    mac: ENC[AES256_GCM,data:ntS9OEl4AjWrFTwbm4vl13XN6y8EE1Ozlo1lYN/lOGtjztBDdvpNoZGOyeqLwyszXw7HldVygp0Lbu795wz+9bARAN4LTA59pEAC/z5wr6QXhq4Tfbk0EsZPUw2c4rARsk9XUBR0cNcoerZnDA9Jl3QKPYANvd8P1HpgEl/ty1w=,iv:xr05L5uanrTrjqclI4QNO2YSdbt4ejL+JSBTUY4oSuY=,tag:7hES1v5LtROB/EvlwXmV8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
