apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-secret
    namespace: database
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:pGP4DKAO1eKU,iv:ZVT/3nF5ADITKJ0ZoClXoixl2cQmnyR42UwcP0KekDI=,tag:NCfu9uhQWYXGJzW8t+dIVw==,type:str]
    password: ENC[AES256_GCM,data:tGKC8ZU3YU1PYR91rWaqA5yEcvaQFq5pBmLPgbGSPR5dS67H0vSb2kAMWpsxD5fz2j1diXJHAWDjvneFMkc9YQ==,iv:m839gsQvcV7VaHSuX11z+M2z01BGS3bfTwqFEeUnQvY=,tag:trL7VzEL9uNJpjo9xHcICg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3R1VuYXZWVTlkZ2JHVHJ0
            ZWVDM3krQjVrN3ZaZC9COEFJejNqdGt3aFZNCmF5N2FINWwwOTlFWjB0VHd2aE4w
            VlVILzMvd3RUd2RzcmxnV1Z1bExpeG8KLS0tIDFIa2FEWVkwQzczbW5TVDZXelNm
            Q3Z3aXJZL3doUVZZR1RVSDJnQmpQSkUKxfPlpYZUPPOVwmxO8Ec6chymYVU376ma
            0og92S7gusU0KwCsiRDIFY5Qpl7HIzYC4n9b7HQf/kjR+e8IzKo7qA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-05T17:19:05Z"
    mac: ENC[AES256_GCM,data:IKTNi46SH474loHZmG7zIogkYrnknRGB+zA6lKR6Jt9I0kM00/bti57oVXXAS1oEYisb0B+RgqLvTG6L9a1ny3zBMY9W+rjeI5Ybn65tEgGI0eutyGGf5IG0YRiaq8uq2KKlMf7q+m0+36HTrgFcKR4M7kR52cBhX1zHn0YyJ5U=,iv:di4oOZIWOfBo540+uFWHIZW/SrxZ92+appM6FQCMmYA=,tag:SwX4KyvcossaaBIbnYxtvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
