apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-main
  namespace: database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.0
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: longhorn-fast-single
  affinity:
    nodeSelector:
      hardware.home/storage: nvme
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-db-secret
  superuserSecret:
    name: postgres-main-superuser
  monitoring:
    enablePodMonitor: true
