apiVersion: v1
kind: Namespace
metadata:
    name: cloudflared
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUWw2QzhIUTZHRGhTMGZp
            bFA4aWIxQ2ZqWWs4MWM0T2lGNTg1N0NPMG0wClBGaGhGak45Y2lGeDZEeFJxNFR4
            UGw0VlhnT3hsaGtoNi9yTDJqN3VudDQKLS0tIGhZUitHTHZHY3BzSlhuS1EvbUp0
            cng3NjFXS2xRRGh1UHgrSWhDcDJ6N2sKq1jDILS6j9gWSNAqaRsFfPNV4zc7nnJS
            1VkUQIIAr82tTKKZCx8HdmuUhk7tfq1B8J40OUnnuU8pdbnIESJd4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:35:39Z"
    mac: ENC[AES256_GCM,data:IDrWCs6Bo57Q6KlX7nLdYcPsPdrALJzyH2JVF9tnJgQ2saX1Y4zdQ/GPWWFso9mzbTd11sdu2QOeN1vq1ZXNdBQmjjGoaaZfHtYRKtgq1jWlpcoxrHsnfVszpOHn1SzhBJxeUhOnDO/fLTDu68NKdyfUYv/OxqvM/D7wlhB6G3Y=,iv:Z5+TZHSgo50ylvE2sEWKrldPteoA8eMq7deaQjEPK3U=,tag:diiuozQRd4cxyCLVzHovtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:IrLQy3vZpN1M4sZB75CZ4+BSbrG2yynv/sqjKhYXBclWKR8cc9NQIkgpa6SJrv/tQdMjad2euCVYqSRnTGEGIe2TuvgZj0biInbepyaiadPsUMmsuti2kmN4BfdODWcsJxRF+ZaZDFRk2RkNIwzL9jG2ocFi7VgQTN6YFgcvlJ6Y8fGjEo5BhfyIEooenVgFkgeM2Ux3UO9TY4FZUwwF98nYXCHCt9mo/f8AkIgr9iWUbFKBTFJuVA==,iv:pd0yMdUYbFEnnRtrMshxp7BkBW214QdclsnRzwHrZPk=,tag:vxj0bAN8DmaV20/JKFtFVw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMUWw2QzhIUTZHRGhTMGZp
            bFA4aWIxQ2ZqWWs4MWM0T2lGNTg1N0NPMG0wClBGaGhGak45Y2lGeDZEeFJxNFR4
            UGw0VlhnT3hsaGtoNi9yTDJqN3VudDQKLS0tIGhZUitHTHZHY3BzSlhuS1EvbUp0
            cng3NjFXS2xRRGh1UHgrSWhDcDJ6N2sKq1jDILS6j9gWSNAqaRsFfPNV4zc7nnJS
            1VkUQIIAr82tTKKZCx8HdmuUhk7tfq1B8J40OUnnuU8pdbnIESJd4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:35:39Z"
    mac: ENC[AES256_GCM,data:IDrWCs6Bo57Q6KlX7nLdYcPsPdrALJzyH2JVF9tnJgQ2saX1Y4zdQ/GPWWFso9mzbTd11sdu2QOeN1vq1ZXNdBQmjjGoaaZfHtYRKtgq1jWlpcoxrHsnfVszpOHn1SzhBJxeUhOnDO/fLTDu68NKdyfUYv/OxqvM/D7wlhB6G3Y=,iv:Z5+TZHSgo50ylvE2sEWKrldPteoA8eMq7deaQjEPK3U=,tag:diiuozQRd4cxyCLVzHovtw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
