apiVersion: v1
kind: Namespace
metadata:
    name: cloudflared
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WW1wTVg4MnVKWlpScEJJ
            czNmM3JLK1hzRTBoUzVyblc4VUNiRmZCSXljCitEUngrWHh6NzArbmFlbDJUanBZ
            bFhoZjNjSHBLODRpcWpaY3dYOGdPYUUKLS0tIHh1bEJ0eEk4VWJqVFRLZ1hBUzJi
            bU9GK0JKT25PSlFRWk9xeGdXd25SblEK8izPWur9wAhZw1L72p7kyJmT3GLrtjy5
            6j8WfVFQCZpItrcVuPLlLWxUXrn0ancNoFrIQZCQEGggc1htytUncA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:43:18Z"
    mac: ENC[AES256_GCM,data:ZF9s9wgAuO7wiphwusycNLD3YtavDYwCJXlmuk7akHmCj7cF9FLLKOK6B/HYE5LOvkDrDxVQbhhZ9vpWAe/VgEjjozLBNfCsKlzfii3wPS2GCRF4sRUWZVutv1AbMS9R1rdHeWgQpUHjCWFmTniPnN+KLj+2ok+HklMzW2+AhMA=,iv:j/ADt/WRyxl6401CJgGtbauT8C+Q38CVb5rYAHFbYwI=,tag:kmQhSN+4+kvACme27udWJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:gc3rm7DNyZV/X2JyM9lMU2wPTXHtXs7r1V0IFfUDhJYIn/pHz+9ur8DArX6tKdjnuGdex4307P5sQ8lV7jUb3MD9VIMjTtt8VL2H4T6V4OjMSPGlMZDpInG0mQcvZdtvPcdUMlfgEoqmcYOdBridrzTJ48BZaaiUVBx4Jz9mrDQDfClPkZNvkTz4l22cu6NrGQNmMSmnHo5mhE+k4B7xh6lOy9ajryEuBTlysAFRB0NgG4eu5ubg6g==,iv:j1Eei0x6bUCL2/AUJ6fUmVvZFLfz2kRBNkYy89HP8mI=,tag:sMify27kSr2fgYl7TEDgJQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WW1wTVg4MnVKWlpScEJJ
            czNmM3JLK1hzRTBoUzVyblc4VUNiRmZCSXljCitEUngrWHh6NzArbmFlbDJUanBZ
            bFhoZjNjSHBLODRpcWpaY3dYOGdPYUUKLS0tIHh1bEJ0eEk4VWJqVFRLZ1hBUzJi
            bU9GK0JKT25PSlFRWk9xeGdXd25SblEK8izPWur9wAhZw1L72p7kyJmT3GLrtjy5
            6j8WfVFQCZpItrcVuPLlLWxUXrn0ancNoFrIQZCQEGggc1htytUncA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T19:43:18Z"
    mac: ENC[AES256_GCM,data:ZF9s9wgAuO7wiphwusycNLD3YtavDYwCJXlmuk7akHmCj7cF9FLLKOK6B/HYE5LOvkDrDxVQbhhZ9vpWAe/VgEjjozLBNfCsKlzfii3wPS2GCRF4sRUWZVutv1AbMS9R1rdHeWgQpUHjCWFmTniPnN+KLj+2ok+HklMzW2+AhMA=,iv:j/ADt/WRyxl6401CJgGtbauT8C+Q38CVb5rYAHFbYwI=,tag:kmQhSN+4+kvACme27udWJA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
