apiVersion: v1
kind: Namespace
metadata:
    name: cloudflared
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbmo1WC8zUCtjYlRaeE5n
            dTFYejBhZXlxSklienRNYm9vbiswSDRLdjNzCkQxQTBWcmlDcmtYaW0zb1A4UTZ2
            ZnJwMCs2RUx4RWJWbnROckpRV3lNMmsKLS0tIGlIMG9kYTh4TG01ajJaRzdVOXBF
            QjNSaGlwZk1tclhDcHl0Rkk1biswMjAKkWC8sN8ZQZ407GhHg806F+yP6/v5S5Eh
            XyWXWuxHBdQMs1u3Yrq9M0SuXSShSvSuH9p9Vq8/eksV5wOUaN1DQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T22:36:56Z"
    mac: ENC[AES256_GCM,data:Iakatc5yyRsgmfCVZ1nKMtY17shhLIL7vWiEDqvTNFTTMEfsa+fMSwimGIlBl1e5eoPVDnjAlK+E3/oWn6xPHROd8xaYGgOeMwK3ygktVGB90NQGEOPmiVtdhx0/nkIG3Y94EwtAzI1u1UBdJ83iBUp/iMMS0asjkN1wvNC1W8U=,iv:1jUMUPLwZUPjfefeXcxnbV8dUOyYwlecaTnTPY2G+dE=,tag:nqRH/u13Fgwuy0g4cDVDgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:dvijGi2XjIG757KgTPmDX1QLAiHLolZH79MSRuLD50tYVSNq8x3d29TFXCiUUu3Z3py5EDy+iVdDIhx1XTRX+WJ/TXWWpZuca+c6mSOILDzOA8M/zZbDbaY0F8HZu7b8uwFwseHo6TBq5bwWEkLM87z9wdkW7CpQ6HUaCeAmK8Niydnz3+6TwTPgYdSNLylVj66o9aSIDDrqKLmeE98Viv1xTTY0JP6qlAN0KOlXgHfo2QbHowyslA==,iv:mGjlTBlivo+lXu+NnZ9OfafP89LWODS+ql07jgZgkF4=,tag:zU/9car5ku12IvTCLPV/+A==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbmo1WC8zUCtjYlRaeE5n
            dTFYejBhZXlxSklienRNYm9vbiswSDRLdjNzCkQxQTBWcmlDcmtYaW0zb1A4UTZ2
            ZnJwMCs2RUx4RWJWbnROckpRV3lNMmsKLS0tIGlIMG9kYTh4TG01ajJaRzdVOXBF
            QjNSaGlwZk1tclhDcHl0Rkk1biswMjAKkWC8sN8ZQZ407GhHg806F+yP6/v5S5Eh
            XyWXWuxHBdQMs1u3Yrq9M0SuXSShSvSuH9p9Vq8/eksV5wOUaN1DQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T22:36:56Z"
    mac: ENC[AES256_GCM,data:Iakatc5yyRsgmfCVZ1nKMtY17shhLIL7vWiEDqvTNFTTMEfsa+fMSwimGIlBl1e5eoPVDnjAlK+E3/oWn6xPHROd8xaYGgOeMwK3ygktVGB90NQGEOPmiVtdhx0/nkIG3Y94EwtAzI1u1UBdJ83iBUp/iMMS0asjkN1wvNC1W8U=,iv:1jUMUPLwZUPjfefeXcxnbV8dUOyYwlecaTnTPY2G+dE=,tag:nqRH/u13Fgwuy0g4cDVDgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
