apiVersion: v1
kind: Namespace
metadata:
    name: cloudflared
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ekNTamhlZ3REZXF3WktU
            UXlEbUdGMzVyTjdTeW11SDdiN0J5azUxSm1zCmczOVlZV3pQZC93TktlY1h3MWdl
            NUwvMFE1eWszZzNGR2lseUZ0RHI3UUkKLS0tIHJ0Y0ozSnQ4czFZUVpQbFl5bzJD
            dkJaUi9IMkhGdFB2MTJuN2xFWkJpem8KWeN0frFGJwxzwV7/cc2kjNs9i8avWVFw
            APVsQskeKtghJGK9mHswKWBxMSR10JUoCt044pnTb0WIps5w7rVxuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:34:09Z"
    mac: ENC[AES256_GCM,data:PTqsZKoNVnKHMp9RojJVYmWz4TyySO6H0mT8ml4WMcvJcTcRfILiMRl3rtMzmhD5GkXyqKiWXJLVVtXOxu1U2Fhu5oDzz2n1DQs5xjyjfYJJ4tRwe+CSup4a0XxqQLLhbghRcPIUY0hn/5adjFjeGJBDUNSUjpuNiqDTPKsi05A=,iv:VQ22ZTAdhV0ad53KPI1iqNliazw3I820bVul7ZT7gEc=,tag:TjXkdQlStUI1UBPWdgUZ2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:ojqUq+oGtAJRRBOLXf/nm5nJqYMtOUKdc+u77H4SVhRKMfg3EuICYWFjhSJyjWYA0tUrs52D1KJcQ6JznH52CQhW6j/a/8vaAKFS/ncWi48nF3wOvyCal59RwJ/wN6xxazUGHd837thV5uaiQzxq9oMGs06rA/yWZiKJ/JKo5sHZvae+pHjG0F7Hh7KSamLKNYUgnucx2fVlEtwVqlRLrKiJADwLKV6N8JTWkCCa+nqEIsNuE8ivyg==,iv:qFiugO+XddIqkTSLm376dn4CLyL93ZBSLw+rLrIum68=,tag:aliSTZ9HLS2QMLs2FAx8Qg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ekNTamhlZ3REZXF3WktU
            UXlEbUdGMzVyTjdTeW11SDdiN0J5azUxSm1zCmczOVlZV3pQZC93TktlY1h3MWdl
            NUwvMFE1eWszZzNGR2lseUZ0RHI3UUkKLS0tIHJ0Y0ozSnQ4czFZUVpQbFl5bzJD
            dkJaUi9IMkhGdFB2MTJuN2xFWkJpem8KWeN0frFGJwxzwV7/cc2kjNs9i8avWVFw
            APVsQskeKtghJGK9mHswKWBxMSR10JUoCt044pnTb0WIps5w7rVxuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:34:09Z"
    mac: ENC[AES256_GCM,data:PTqsZKoNVnKHMp9RojJVYmWz4TyySO6H0mT8ml4WMcvJcTcRfILiMRl3rtMzmhD5GkXyqKiWXJLVVtXOxu1U2Fhu5oDzz2n1DQs5xjyjfYJJ4tRwe+CSup4a0XxqQLLhbghRcPIUY0hn/5adjFjeGJBDUNSUjpuNiqDTPKsi05A=,iv:VQ22ZTAdhV0ad53KPI1iqNliazw3I820bVul7ZT7gEc=,tag:TjXkdQlStUI1UBPWdgUZ2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
