apiVersion: v1
kind: Namespace
metadata:
    name: cloudflared
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVlp3ZWdpaUc1bElNUG1Y
            b25oc081ZGltTGk0Rjd5WDRUMUIwVGRuWXcwCmZYN0lweHc0NHVDZ3VhMnpRMlo2
            YTBTMU81UEpmbUxETUc5WHN2czliNGsKLS0tIHczWUFaQ2hsZnVSRmJ6SURSTWlk
            YjZBdzg0Q2VOZEVtYnU3V0xCOUxycDgKs3PHFAWvuFErGRB6FbyZl5ualxsKk6py
            nzkzQxaJzkuVjF9PqTBKR7XrBHJYbQkYMja0WNNAMWvWcV+w4SYmsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T18:04:39Z"
    mac: ENC[AES256_GCM,data:pGQHH2aAZG49K12Zs831WiRQhds4ViAt+c4K36bSAZXHiXyNQ9/BE8U7C0RfseN1rBwOpeyeBJ3HaLwtgO/a98sjeVbagTjeJtgwp14iuOP8XqvcFkqEFcUj6tsw1Gf1Vq3NnOHrdW88rGKobleVUTaJpzIPM3ICtrZ52G9dRJ4=,iv:P2GvCHxOtj0/T7q2eHnTntcsUGJtXx5qfDosDNqycIo=,tag:UIR0xj+8a/d5RxTLUdeqxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:sc5whrgTACyrY4dCShAVwJ+a4sUg9SM1ACQjeXKRisHpEZ4EqWZJC+tnEBa8LauxJQiagCh2tCyepPSKJaIzV5zI2u8jo7f9ZckdRcRi4b1n/EgN7xav+x8GkH9VdHL/P7jl71yLFkSBamoPQwLLt+E07ihkHC/k/T7csP3uYs4hqDbHvdtNikM10oda2M3bfcKyOcnLUKTTxiVskapIQk70npachfP3glZFuNF2RdwNZ2C9l1NYZw==,iv:2fPdBQKLBuVyTQvqcLefhaot11gKDXuXJV/N7qSTMRY=,tag:iSLgNoh30qwx+vjp0D+BbA==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVlp3ZWdpaUc1bElNUG1Y
            b25oc081ZGltTGk0Rjd5WDRUMUIwVGRuWXcwCmZYN0lweHc0NHVDZ3VhMnpRMlo2
            YTBTMU81UEpmbUxETUc5WHN2czliNGsKLS0tIHczWUFaQ2hsZnVSRmJ6SURSTWlk
            YjZBdzg0Q2VOZEVtYnU3V0xCOUxycDgKs3PHFAWvuFErGRB6FbyZl5ualxsKk6py
            nzkzQxaJzkuVjF9PqTBKR7XrBHJYbQkYMja0WNNAMWvWcV+w4SYmsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T18:04:39Z"
    mac: ENC[AES256_GCM,data:pGQHH2aAZG49K12Zs831WiRQhds4ViAt+c4K36bSAZXHiXyNQ9/BE8U7C0RfseN1rBwOpeyeBJ3HaLwtgO/a98sjeVbagTjeJtgwp14iuOP8XqvcFkqEFcUj6tsw1Gf1Vq3NnOHrdW88rGKobleVUTaJpzIPM3ICtrZ52G9dRJ4=,iv:P2GvCHxOtj0/T7q2eHnTntcsUGJtXx5qfDosDNqycIo=,tag:UIR0xj+8a/d5RxTLUdeqxA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
