apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zitadel-cnpg
  namespace: zitadel
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  bootstrap:
    initdb:
      import:
        type: microservice
        databases:
          - zitadel
        source:
          externalCluster: zitadel-bitnami
  externalClusters:
    - name: zitadel-bitnami
      connectionParameters:
        host: zitadel-postgresql
        user: postgres
        dbname: zitadel
      password:
        name: zitadel-secret
        key: root_password

  storage:
    size: 10Gi
    storageClass: longhorn-fast-single
