apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.22
    path: /mnt/media 
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" 
  resources:
    requests:
      storage: 1Ti
  volumeName: jellyfin-media-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-qnap-pv
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 192.168.0.11
    path: /Public 
  mountOptions:
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-qnap-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: "" 
  resources:
    requests:
      storage: 1Ti
  volumeName: jellyfin-media-qnap-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi