kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-fast-single
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain 
volumeBindingMode: WaitForFirstConsumer 
parameters:
  numberOfReplicas: "1"        
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "strict-local" 
  recurringJobs: |
    [
      {
        "name":"daily-snapshot",
        "task":"snapshot",
        "cron":"0 0 * * *",
        "retain":3
      }
    ]
