apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-services
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/infrastructure/services
  prune: true
  wait: true
  dependsOn: 
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
