apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-emoh-pl
  namespace: traefik-system
spec:
  secretName: wildcard-emoh-pl-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - "emoh.pl"
    - "*.emoh.pl"
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
