apiVersion: v1
kind: Secret
metadata:
    name: zitadel-secret
    namespace: zitadel
stringData:
    masterkey: ENC[AES256_GCM,data:hoLov4vMwtWxgMlpoEzdUAfqSwWFsypnSL75wzaliK4=,iv:ZNPgig7cZkdBZTblE6xIpMmJy+od3AwY0KH8LJvV8Js=,tag:Usr4PQPPR1XboZAq5/7ALQ==,type:str]
    db_password: ENC[AES256_GCM,data:ln2w8OgzuAMpnxeMv5DCKsDvLvSJzFqswy/G0yqBp0yzCthDJBBdSpGegbu5KanfXKum1BYL9O6JOwtwm8QPgw==,iv:NecbbTxf/pe1vTujiB5cblPFd9rhs/9Rw+2JwwfgTxk=,tag:DFQoKbX/TIKOdLO1sqzXwA==,type:str]
    root_password: ENC[AES256_GCM,data:xQCOhjpsbTVeLjNGunilqZ57wrFtk099CaMq6HtEJLnOPoBskozo86IDP0Znu7ALyC/8jLsAPxd/uochu+I23Q==,iv:pyz1Dz9/rAetEDZzdp3QAv7dHj5jiA0Y5a9+jEoyuSY=,tag:HSt50THtECl58O4WdL9HCw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSElrUVo1a2FZa0t0dUVG
            UUVXK0FoZGNiY2JRVGo5YThuZUlMMG5xcDFzClFoblNmYTZUMVdueUovWEhMVTJl
            QkMzODdNMUZzNk9vSXUyK1BaTk1sYnMKLS0tIEFEUUNHaHk5d3Y3aFNBcmxHOVpt
            bnNJTzF1TW1tNGJHbUhZWGcybTBhdW8KLE+9IBbQqyVQa0SeJnsaNbE3AMKfXbkc
            nxS6dSqkYR5guExdKcoe7TE3MDoplS9hHY3dCnJxj0Ehtc6aqSifsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T10:45:44Z"
    mac: ENC[AES256_GCM,data:1LWjRmq+gEyGM2c6nERNalpYnOZFWw7gt94ST//K1v0U9I2MBEUH/Oc6lFKD6xp8gOkId0HPbGum2AabPAaR9JzX2+heAQW81dQePGL5XiSrfYpQwCvdqLaolcg4DLsjj1Zir/g4FIatvG/xSdCRVnOuuG7weLqfh5j5CxYPUkI=,iv:qmImIPHHIE/yVTPct1ELhFX1+TcQCs7stQbG6qs0TYA=,tag:3Lp8dJgejmVyo6I/t7oQpw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
