---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: zitadel
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.zitadel.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zitadel
  namespace: zitadel
spec:
  interval: 1h
  chart:
    spec:
      chart: zitadel
      version: "9.x.x" 
      sourceRef:
        kind: HelmRepository
        name: zitadel
        namespace: flux-system
  targetNamespace: zitadel
  install:
    createNamespace: true
  values:
    postgresql:
      enabled: false
    zitadel:
      masterkeySecretName: "zitadel-secret"
      db:
        host: "zitadel-postgresql" 
        port: 5432
        database: "zitadel"
        user: "zitadel"
        ssl:
          mode: "disable"
      configmapConfig:
        ExternalDomain: "auth.home"
        ExternalSecure: false 
        ExternalPort: 80
        Database:
          Postgres:
            Host: zitadel-postgresql 
            Port: 5432
            Database: zitadel
            User:
              Username: zitadel
              SSL:
                Mode: disable
            Admin:
              Username: postgres
              SSL:
                Mode: disable
        secretConfig:
      Database:
        Postgres:
          User:
            Password:
              valueFrom:
                secretKeyRef:
                  name: "zitadel-secret"
                  key: "db_password"
          Admin:
            Password:
              valueFrom:
                secretKeyRef:
                  name: "zitadel-secret"
                  key: "root_password"
    replicaCount: 1
    nodeSelector:
      hardware.home/tier: performance
      hardware.home/storage: nvme
    initJob:
      nodeSelector:
        hardware.home/tier: performance
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: auth.home
          paths:
            - path: /
              pathType: Prefix
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        memory: 800Mi