---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: zitadel
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.zitadel.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zitadel
  namespace: zitadel
spec:
  interval: 1h
  chart:
    spec:
      chart: zitadel
      version: "9.x.x" 
      sourceRef:
        kind: HelmRepository
        name: zitadel
        namespace: flux-system
  targetNamespace: zitadel
  install:
    createNamespace: true
  values:
    zitadel:
      masterkeySecretName: "zitadel-secret"
      db:
        host: "zitadel-postgresql" 
        port: 5432
        database: "zitadel"
        user: "zitadel"
        ssl:
          mode: "disable"
      configmapConfig:
        ExternalDomain: "auth.home"
        ExternalSecure: false 
        ExternalPort: 80
    postgresql:
      enabled: true
      auth:
        database: zitadel
        username: zitadel
        existingSecret: "zitadel-secret"
        secretKeys:
          userPasswordKey: "db_password"
          adminPasswordKey: "root_password"
      primary:
        persistence:
          enabled: true
          storageClass: "longhorn-fast-single" 
          size: 10Gi
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            memory: 1024Mi
        nodeSelector:
          hardware.home/tier: performance
          hardware.home/storage: nvme
    replicaCount: 1
    nodeSelector:
      hardware.home/tier: performance
      hardware.home/storage: nvme
    initJob:
      annotations:
        "helm.sh/hook": post-install,post-upgrade
      nodeSelector:
        hardware.home/tier: performance
    ingress:
      enabled: true
      className: traefik
      hosts:
        - host: auth.home
          paths:
            - path: /
              pathType: Prefix
    resources:
      requests:
        cpu: 100m
        memory: 300Mi
      limits:
        memory: 800Mi