apiVersion: v1
kind: Secret
metadata:
    name: zitadel-secret
    namespace: zitadel
stringData:
    masterkey: ENC[AES256_GCM,data:iaKb/DVjB6OOO9Uiki7VJ5U476x/Q19qD4WjMEWMBFeoTZktY4ag2RGYUSm/Lp3iJD24ralkNmrd7BjTw7guzQ==,iv:+8dd8oT3zyYONup4SzCqx9h8EdBaPv/k3gPrY9ud5uo=,tag:A6RNpsgFHAJGOrp9RJJ6ZA==,type:str]
    db_password: ENC[AES256_GCM,data:S8rPfnEVslkPHzdbw/1hycGeSOmkzAuKaVhlLIqJ04UyKgHj3n5irXbzAN7SjyNLOO+pOXUqxkbHar1rCrew2g==,iv:6uRTW76Ufiov4b3d2gUOq5TeDmGeZG4f18AP3GT51Jw=,tag:GgFfxIXr/7DUQWLF+bLVMg==,type:str]
    root_password: ENC[AES256_GCM,data:TJjy+oqcF1CoXBTJebUWujom/6wY0oIykF58utv5B2+mkuAFRPUVG99bPWbJ8sThUMPpcgnTDDlCcdXDmJRLGg==,iv:kDCSIZFi6Tvj3ax5IvNB/J2KBI0rn/7qkiRnLbp4unY=,tag:8oPqLhfcUzdJYirje0Iiyw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdjZ0TnJwcWxNT3dScWZo
            L1lCL2l4eVFROGsreGVSbnlHVWVTTjJUclR3CkpRZlpmUERvT1QrOFRFNTlaQWlF
            WXMwTlhhb1ovdXlJRDIwczVtOWp5eUkKLS0tIE1HdlZFekExMEhQTlRqRkphckNh
            ZmpCU0tZMFhqMGptODNZVEJsdjhjcHcKK5VS8sjYoZYG0p+pVAKrP3+v0FTugup/
            PXXReBl4KIWg3+GdS+gIveUoRW5QZEJsfLmBZNblmJjbupnI0RnLzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-20T19:41:00Z"
    mac: ENC[AES256_GCM,data:19TLgNOIhxo8wjr80Gr4bworxbgn+H9Qgwk214px8mFTOIbuaSjJ3i1wmO/cC4A6u3NooLyJrjS7JgVys+bHbFyhfMlVu3NiAcyaiFQOHvBl/HXtLxy7Ag4zDhQGbIdffwQi08U282EbClZgH0FzyVUvMRqk5yVqtbUbO2SeC4w=,iv:rG1UcFVBTiNDsDNuUidky2SwquHxhKE/YVJtEukr8O0=,tag:DBI1OLh4qVAVY8fHMzaV4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
