apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:IeDwDTeWp/qqmW6QSHTftSycen9bvacg7kjrwdg322hUxAYq4AvTCA==,iv:Kf+22+7et3T0BVHeWsNR+dRThUGtBn4BnEEI/62YUZk=,tag:M7/0hcM4u1/XL83Ym35nLw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc1dFWFNmTC9uYWlPcExB
            WmkyK0RGL1NQQXhGQmk0TjJ2ZXpzdlpYb2dZCi80UDcyTGs2cGpwUjMxeE55Mk1T
            MCtYSUgwZkhld2NjSG5ucTF4L3VMZG8KLS0tIEhZc09mRy8wenRyT2RXenF3MnR5
            VzVOZElXRU9nVXNqK1NvSVhtalQwdmsKaD6M+RGvElY7/odo8r4cctlZzBFiTw9R
            6VY4OVmnfDUJbjcAMneiKdUa7acmVJwc8dNj1CZ1W4JE9fWgrIWQJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T19:16:31Z"
    mac: ENC[AES256_GCM,data:rNRujv3UX3kvu0pL9Ipvcm2sXUftmsYgzljLJFHnVH6Gg1a87nHk/uRbfRSws6q5JthAr8upGiVp77hmbdCJPJ67XVuNBke90V69VKkWDSNNHzvsxFcX1kwsI9uPIQNtfySbSCiL5jyJT0IDoJmkJViHf7s2ptzuCgMIkEyj2EE=,iv:d1URPArNN6AO20nFlGsJa5RAXMQ/yXdKMKdw+m9w9u0=,tag:uMS4lXiFuGhl9DbfpLgpZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
