apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:8jGwb+BvQbBWEpPcN9KYEkpg4Ynv7GVcHqdNSPJxKXDaN+tQASRxzg==,iv:YYo2gSJpBH6uAiGEP7lhOdMnOGmptRim7pzTjeDbWzA=,tag:EnDCCFSzDHGS6udfQZ6PDQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdkNyNkhxcGF4bXpuYzh6
            Mk9wd0VpSGFpVjVuVzlvZ0NBNmRYUHpGTG44CitzSlN3TDVkMnZ0cVhicDBkZU5K
            bDlyb0NhWEMvcDVzUEp1QW0yeVgzVnMKLS0tIDJpc1Z4Q0s5SWxlZEtiM1hYK0tR
            U0h3OFRYeENuazQ3dzREL3pvYUhuN3MK6EPnEkJ7FpKcRNkiu5eyqUCxDyWGjIa+
            IYBUrMewlqAQErJsYBmFpbgUvWIGc2EIiGS+aZGIsCvePYvvqI0YDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:25:09Z"
    mac: ENC[AES256_GCM,data:Q2JQwOpVYG0RqnHM8a+Vg8GK64YkhdinNQKdmvJ0E25MDQGkdhxqR65Y+3Qj8y9A2HdUYXllU26gLS8SVh5VM2wAeZpM9wBwqClzCwhqNB57SLFAxaf1mCrmXA8GwSkb0jajuQQy77pTCQCauMadKTpREoF/U1kPOCycWsrPNOc=,iv:Re34bnlPNmfAUyHFxxe1VL4kWSbq1h++a3w29zV3cSY=,tag:J5xQ4toqakcr8EnamsYbiQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
