apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:IB08iQiOJNinOPYAvO9QkJ0x6LMM5ZwgaDvsXukHQiVbu2EEmbsu1g==,iv:tD4Gjr+JFy94Ay723vuLWyQSRWZV1F6LAMtGopUi/ZE=,tag:Z9sOdV3jdRuLhV/r0zy85Q==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmcFg0azhVSEszeG45TFhz
            bDl6aVc3VzhJZEtKbXRPY2ZlSlcrY0RoUFVrCjFLYit3SGZGaU9JZUhmMkdwZkZP
            dlExMmV0QVNQSVA0M1hDdEN1Q21mdXMKLS0tIG1GQ09RRjJleVRISU4zMWZ0K1VC
            UnN1YkRIK1YvOGUvNG5UcjQ3dk5QQVkKfmIw0FNVsAIUJ9Jf2zoKSnd8cVNHG5v9
            /OwvjR/kRHbYh3g+I+HhRe/nxElAE0k50uHtkI3cMVZngIz0wVRxQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:34:09Z"
    mac: ENC[AES256_GCM,data:dP7yP+H1qyttHfmj5HW858IaUEXQB7n8NZhIeCWHcs9fYj3wRZMD+XnODDQfu4nTp20DGi5vpq5odUHlLpvNmiGRm//pEMpbm/x5VswPRmMSUDhBaSbprUU2c3wrDrwwGl4rq9akCXlmtXoEIZffx86/TiLruR9w2F1tseg38k8=,iv:wAa8zf33mhxVIF1PksIRA6qEVPPuHCPLbqXsuL7cm9c=,tag:bc23UWDBSQaeFtYpcvW8NQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
