apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:6z5rU6nDWvncVhHNB1O+DPl8lkEVd3VYhoojauHR+YS6Z27AO5d3BA==,iv:+pjdSaK4KPyXWe90Cc7rFdPSUBekVufXDhe4cFyXvms=,tag:/DplEMElC6YOq0q5qbbu7A==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVEM2aE5abzBmNWdLU3pq
            UlBCUTNlM01nNjc0aSt4bGdvSlZCQTdSMUhJCk9kanpLMWtXVm4xRjU4dWJ1ekFE
            eXlwRHBXbU9kVUw1L1JzNkoyK1B5SjAKLS0tIEFQVHpXTUVoYVZpcldyU1NZNzNC
            R1prRHVTK1Jma0pUNnBqWkNMUHlSVkEKW5qJcLUkK0Tcvwx3HujuiwjqJ3NUE682
            BJtOCK1D66y4bRN+2gbR8wGCw1r2YriszhR7hPIgE18Uoi1AeZoHfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T18:57:48Z"
    mac: ENC[AES256_GCM,data:DVHwiyO2oc8cTAWQbYE3KZzeuSorx0jayeu2b3p+ts5dIUfYPQf+OcOVzsriS+y+hiPcm9e6tgciQo518OPBofOMhQ05nUBg/B157ueyXKis0rCce0mCXgX4PfnkRZnWIraKqxvwyRPiT5Xae59sdAr70tedwVAZ1nRMf1RD1GI=,iv:GIEmLnegv2axyQdCpMpXwZkDuCDDdkx9qIrxPK2QB8I=,tag:mI/XldbdYz3OTRHXETYeJw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
