apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: scrums.stapler_6o@icloud.com
    privateKeySecretRef:
      name: letsencrypt-dns-private-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
      selector:
        dnsZones:
          - emoh.pl
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-emoh-pl
  namespace: traefik-system
spec:
  secretName: wildcard-emoh-pl-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
    - "emoh.pl"
    - "*.emoh.pl"
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days

