apiVersion: v1
kind: Namespace
metadata:
    name: cloudflared
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWlZRSFVFc0FCTFZFVnUv
            UFhLZzErOHNueS9zUVBhc2NGNDUvcFVIRVFBCkpUSzZSbjBFM0hyU3J1Yk9hRDY0
            ZXlrRUQzbkFHQitxL0JIRW9Gakdkb2sKLS0tIHpiaXVmdXRubnZHUlZsK1dyTlpX
            cU5lZXR5WDhWeWdqd3BreE9TdjlFVUEK1sWDyAgwNudstZ7ZDhC5BmPWWVLurxOk
            ctY3coU0+9zggVZRRP+cvNJQTqnU4Mx3+f5Pcuu8/3uFhzxBWzwwwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T18:57:48Z"
    mac: ENC[AES256_GCM,data:637ujyxOnqH8ZPcK0vu7IDF373X+1mSRmCkFA/4URYFRRpwg2KNNDiZZAGRUu3IE3hy6O4eHsYqGZfXDlyKZWBzx7EF0zCPOzwqrWnMHwwUuzt6MJokzEQFH6QSXFWC4tsnOiJH79zMKxGflLKKFVKNHTwvMCKEYYQ3WtXutHFo=,iv:RdkVzZqDX5j3EyHo+yTkyekrldYHFcdhS9uKk6oGYbQ=,tag:nXhcQWykU9PAQWbRKN7wRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:vlQ0wwxDVn8nXN+jgtR9hWsHL5RpDChWTz83rPg=,iv:BM+A7+6mov/N7yML8b2dRr+oHVcGWLir7KuzOjI78eM=,tag:Ge0JiPE744qRcQ2pfZx3/w==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWlZRSFVFc0FCTFZFVnUv
            UFhLZzErOHNueS9zUVBhc2NGNDUvcFVIRVFBCkpUSzZSbjBFM0hyU3J1Yk9hRDY0
            ZXlrRUQzbkFHQitxL0JIRW9Gakdkb2sKLS0tIHpiaXVmdXRubnZHUlZsK1dyTlpX
            cU5lZXR5WDhWeWdqd3BreE9TdjlFVUEK1sWDyAgwNudstZ7ZDhC5BmPWWVLurxOk
            ctY3coU0+9zggVZRRP+cvNJQTqnU4Mx3+f5Pcuu8/3uFhzxBWzwwwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T18:57:48Z"
    mac: ENC[AES256_GCM,data:637ujyxOnqH8ZPcK0vu7IDF373X+1mSRmCkFA/4URYFRRpwg2KNNDiZZAGRUu3IE3hy6O4eHsYqGZfXDlyKZWBzx7EF0zCPOzwqrWnMHwwUuzt6MJokzEQFH6QSXFWC4tsnOiJH79zMKxGflLKKFVKNHTwvMCKEYYQ3WtXutHFo=,iv:RdkVzZqDX5j3EyHo+yTkyekrldYHFcdhS9uKk6oGYbQ=,tag:nXhcQWykU9PAQWbRKN7wRw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
