apiVersion: v1
kind: Namespace
metadata:
    name: cloudflared
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VktGQStzNEVFZ1ZYajIw
            M1NreVMrNy9XMU10NUxVVUxhSXU1c2RDb1cwCkVWbUl1eEFWMFArMHhaSDgvWisz
            VG4xSzUxVWFYL0ZGMm1ReHhlcXdYeTQKLS0tIGZrUjNtMWhMbmpzZ2lwb25CRm4z
            Z0ZrWlpsbDNVQXN5UUJmVi9JTDRvdW8KZpL2Sv8sMIeiSvijKbJ3CZZOCsa8B40d
            vSMqISokjCPogKvVlbtJN7/qQHLvlMgErz2bqorh5fed3WOCpB40XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:25:09Z"
    mac: ENC[AES256_GCM,data:A8UAJMZMR30Af0zJtx/dGj57kNe/NnaayS8BlvwaoWIAsquMjKg694WAoyfJZvNQy5EiP6hw2qIa9gtD9kKa4I5h2KeeIN1YgUAWy6wUB6cQ+/WTfPckcfhwHhq3kVzE0N+44mGSAEUpMgchFBx/KjNiP3WZ2Cfy5vPvkrqZH+4=,iv:3rMqChiZQysVa8hBg7a5wYL/igTOXmRZZaD+ATZqXrM=,tag:UOjaQIWt6ASE6UGv8uLpDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:+gihdHv4NRibeZoKet9+9ALO9GrULxe7hNiGCYvIXhqRY6INJtVmdWjZRrnNhN+cZJqO4s4tkD2vLVDOSKZqMxHO/Er+/ELuE7z6g2CmhjKfAoMpNKbijkXnjnK6GUMGlnD7/lYalOWjZj/B0Yxln7m9Mv0deEWyvCjM4cEmnEsFE0n7kW3YcZvZdSPGuykNGstD7NsbPsRQsqTkS7Dl+Ckm/vM3+RGeZf87iMrsr2Gw/RzClaxbYQ==,iv:mvY+Hfro20LFihEg7zYkLEC4Sjd+/AMmz6uggOlxbss=,tag:M+YXKbCS5ave7zkQYiNb0g==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VktGQStzNEVFZ1ZYajIw
            M1NreVMrNy9XMU10NUxVVUxhSXU1c2RDb1cwCkVWbUl1eEFWMFArMHhaSDgvWisz
            VG4xSzUxVWFYL0ZGMm1ReHhlcXdYeTQKLS0tIGZrUjNtMWhMbmpzZ2lwb25CRm4z
            Z0ZrWlpsbDNVQXN5UUJmVi9JTDRvdW8KZpL2Sv8sMIeiSvijKbJ3CZZOCsa8B40d
            vSMqISokjCPogKvVlbtJN7/qQHLvlMgErz2bqorh5fed3WOCpB40XA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:25:09Z"
    mac: ENC[AES256_GCM,data:A8UAJMZMR30Af0zJtx/dGj57kNe/NnaayS8BlvwaoWIAsquMjKg694WAoyfJZvNQy5EiP6hw2qIa9gtD9kKa4I5h2KeeIN1YgUAWy6wUB6cQ+/WTfPckcfhwHhq3kVzE0N+44mGSAEUpMgchFBx/KjNiP3WZ2Cfy5vPvkrqZH+4=,iv:3rMqChiZQysVa8hBg7a5wYL/igTOXmRZZaD+ATZqXrM=,tag:UOjaQIWt6ASE6UGv8uLpDQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
