apiVersion: v1
kind: Namespace
metadata:
    name: cloudflared
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NlFLMTdGYXh6NEZicWRk
            WDhPRmhwRWpLNFYrRytvM3VMQzBueUpXU0JvClRlcmxIb1JaaUJUdXFQV2dQZXY4
            c3ZFMmRvU0h0ZFdETnB5Ti8yMWh3TVEKLS0tIGIzZzhCNk1paGxoOHpoQ3lpVWIw
            Y2xsMzMxL3JSdTZoejIwcDJPT0lJUGMKgbr6/LlRf0rR8F5N4lgO84c0LjXJeAkf
            L8eRuXz0iu6TgAXrte6xOBgDaHQfDdnnYY+jzyOg2/2uKr/GzHb2sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T19:16:31Z"
    mac: ENC[AES256_GCM,data:ItnMKqk5UBpRZmX+uqximMJ6JGfz+JOZh1C+NJUpjNhYktQxTZQU8M9HNz6wjSSaA3qdONAAthlUyA8b8dP/w77Kfr13DR0DrUzUWeD3fP+YuJa8zroD4+H/jN17iKrpncZdWj7NDY95Ofo+avuQBdQbcNwYIMZV7lBa0zU3+XY=,iv:/UXDpdyIfhxSvN6rFdTbUqDgTVxKe6BA2dTq13/ZSFs=,tag:uT7eaI+jf/BmfI6Oz19iMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: cloudflared
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:Be8MbRbBPa78CuuzebkTMDE8VdxMUCPvECt2UnZZLLfE+8KY7U/zCMfwKxrSwY9H9bM9Ct2BuHhprgrRQeVsBtYbmOZLMta5ksSJlPIZx1pixAVEZb7gZvuRiKu9PSPsGn+OrDuXRipkiWckJGjERJWTHApG3K22Fh/5eGkaCzLk1otZQTsxnmscFGImEWWnDVZNfblZibD6RQP8ufbDDB5HgvMluWwgPpytQnY9LHW2Q8jQBxE5pA==,iv:eGaGDSH1zoccKDwgtjttO4ly/ugYZPedlI9iJa766Ws=,tag:sLXv3Beyi7mcGpViM8ZZ8Q==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5NlFLMTdGYXh6NEZicWRk
            WDhPRmhwRWpLNFYrRytvM3VMQzBueUpXU0JvClRlcmxIb1JaaUJUdXFQV2dQZXY4
            c3ZFMmRvU0h0ZFdETnB5Ti8yMWh3TVEKLS0tIGIzZzhCNk1paGxoOHpoQ3lpVWIw
            Y2xsMzMxL3JSdTZoejIwcDJPT0lJUGMKgbr6/LlRf0rR8F5N4lgO84c0LjXJeAkf
            L8eRuXz0iu6TgAXrte6xOBgDaHQfDdnnYY+jzyOg2/2uKr/GzHb2sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T19:16:31Z"
    mac: ENC[AES256_GCM,data:ItnMKqk5UBpRZmX+uqximMJ6JGfz+JOZh1C+NJUpjNhYktQxTZQU8M9HNz6wjSSaA3qdONAAthlUyA8b8dP/w77Kfr13DR0DrUzUWeD3fP+YuJa8zroD4+H/jN17iKrpncZdWj7NDY95Ofo+avuQBdQbcNwYIMZV7lBa0zU3+XY=,iv:/UXDpdyIfhxSvN6rFdTbUqDgTVxKe6BA2dTq13/ZSFs=,tag:uT7eaI+jf/BmfI6Oz19iMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
