
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-gpu-device-plugin
  namespace: flux-system
spec:
  dependsOn:
    - name: intel-device-plugins-operator
  interval: 1h
  chart:
    spec:
      chart: intel-device-plugins-gpu
      version: "0.x.x"
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
  targetNamespace: kube-system
  install:
    createNamespace: false
  values:
    nodeSelector:
      intel.feature.node.kubernetes.io/gpu: "true"
    
    devicePlugin:
      image:
        repository: intel/intel-gpu-plugin
        tag: "0.34.1"
      
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 128Mi
    
    sharedDeviceNumber: 1
