apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager
  - cloudflared
  - cloudnative-pg
  - intel-gpu
  - longhorn
  - metallb
  - metrics-server
  - nfd
  - traefik
