apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-namespace.yaml
  - cert-manager-letsencrypt.yaml
  - cert-manager-issuer.yaml
  - cert-manager-secret.enc.yaml
  - cloudflared.yaml
  - cloudflared-secret.enc.yaml
  - metallb.yaml
  - traefik.yaml
  - longhorn.yaml