apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-creds
    namespace: traefik-system
stringData:
    client-id: ENC[AES256_GCM,data:/c/0XSXQ+7PwTmOpM8xKquIc,iv:NrALoj9DlIYEiG8wtzyj0rL1K8AZuP2eapbgCA09Iio=,tag:WQMKGlVvRBz6wQRpPQjzjA==,type:str]
    client-secret: ENC[AES256_GCM,data:gBvHPd/q3AiDUWEvn6pPjIfq0wvanV6X7OUDAKt5j8+UgVe+xgMSD+/ZFFeAtSodjXI3I0o8jgjGe2BAyyVgmw==,iv:8XM1KynBSi/956A4n+Yy7QgXr7mT8r11QEQjQiGtcMg=,tag:cUumgvDT0Yg+RAHedwWlGA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:feiH/2t6/IPBlJYVTp86kPJMfaaBh6ik2URqhQy6LPUR/pIv9oUDTrDotOU=,iv:ntZawgyKNafl/YOynyz20RuagtOCRGhtq9tKIpKJKRA=,tag:Kh5R4lVIriE33+Iarqqryw==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVEtRMGxwYWNBU3I5L1NZ
            amRaZllSdExIek1IQ0RuaGZqaVZuQUZYOTB3CnVPdzZCQzlSMldvUXVBOSt5cVR6
            UnFGY280bTA1ZVZNU0JqTHBzbXlickEKLS0tIEd3WmIrWG1BblNuWGIza25MZ3Vm
            VWNCUitEWTV5djhsYUVncXYrVWJpcFEKMVqoV2XzySMWQTMCETV1H+YlieWVRuY0
            OH7AgyBMJeMqVqmXrFre9KmiVW4Chag6pznz4Q/FnOc93drmNR8cYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:25:09Z"
    mac: ENC[AES256_GCM,data:zUdf4teK+cyf3xr9myVdRMWOknQhXn88i7X8N+ECI1MkFa/DEo5c56smZl65bBVIwOzTDb7l4cVOEC0+IZ+UalLZfv5NX5H6LMAqlu7MjTTdANBrjGrEiMJqeC1eFl2fBMv2O3DxNp9aqiZGiFryUftWtSkunaraQu4kzuoICzA=,iv:Ou6tx//B4w/CqqwZayzFWonWuoWMFUHmZ1jo97D8Nc8=,tag:t2l1Sdpxnb3rKM3NsD44ag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
