apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-creds
    namespace: traefik-system
stringData:
    client-id: ENC[AES256_GCM,data:rNB2qhxO8u8TGfKuapKWAxsi,iv:BtO45Btc9syRXB1FZeOm9uRCSWAvpgtWKolZg3hz8so=,tag:kkMPYoA7tmdJozTu63fvwg==,type:str]
    client-secret: ENC[AES256_GCM,data:n7J9rUW0o7RwYc0EBnfI0PYmIH+7sNwptQSrxAINu8cn7Y3+zEcmEgayDjXewAJzgoj1CW4lx1AHD6LOJatzKw==,iv:jYs767as3YsoiDdh8rCGxmm2Mr4RaATiC+wGdTncq0s=,tag:X21By3zcEmJKVP/ocKURow==,type:str]
    cookie-secret: ENC[AES256_GCM,data:5sLntC119jObwMvQucUraXjl97VnV0DoHR9SlXdLaRoXT0xk5L/rj+gmJro=,iv:AVmf/1xm1FBuMSjoMhMHO6IEnMrOPlCcdMQ/A7dA4oI=,tag:STmDgUZOBcnAReeXTXmI+g==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNY1VyTHl5RHJBWkZvZStC
            OWxUamJMOXZvcFJhS1lENGV2N2lQZHQzdHg0CjlVV3VtamdoSG95dzc1ZlN3MzZ5
            OUhtcFVLSXNKaVQ2ZjVCVjJnNUwzbWsKLS0tIFRMRGU4YWFWcm5YbzZwZk5FeFVP
            bnFSL1BuQkkrbm10NzJUeFdjTmUxdUUKnmRalBsBV+Q1bmbZkO/8voD+tQJQJ92F
            bRN2h9P4h8iYTEFMtoKmMKAs5XNwthP9LeS3rGxTS7Ji02QYP89jFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T20:01:33Z"
    mac: ENC[AES256_GCM,data:COzndVDfBdBgtSntWcZJ/PSHq/XDqjmMFX0hrgnyNyDWOLe6rbUzlpgYmWhOsJkikDtOS1/lhN+uoWDWMTTg7yIpBu5N9VFkQUUuMRYILiBV+tcpvwzIIx2w6dSY/y0hahkWY2o0MqvWHbfvsGFuqklUcu5jpM/sn11AmzJHZKc=,iv:64j+BmzAwdcMBgsVhetLvEOQnsZxGaTIjnewxgcfcyM=,tag:Q0+6qSTmvgS8iOJzltk1WA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
