apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-creds
    namespace: traefik-system
stringData:
    client-id: ENC[AES256_GCM,data:y0ZYXIQIYNaP+3vruwW/O5Yv,iv:eVNBt11Y3hkV0Jyky05gdzv1yP3/7TJwRXusjhjCwQs=,tag:fuda+FhQ3NySU7HuxDhteA==,type:str]
    client-secret: ENC[AES256_GCM,data:QoZzqkyWMVfULF4oDpK7emDiSDHboGOGhQuIsTfKcbU4hfnBMcG4kQob5pGrlmcsBKSh6JQi0cgNXeX31K7qHQ==,iv:xKcY7NOUc+POkirFzUB1ksXjexszwzBvQHS8gliRtsc=,tag:RGpkc+HNype/UZ2ubdBqyw==,type:str]
    cookie-secret: ENC[AES256_GCM,data:YrVU5uZXk/79fKx3//YrLZ8cv5zCvD1jmMRj51sMdJTUBOxndXAraYi6H/c=,iv:A1rI7xbxqa5JVCl600Nb/LmGFp5KeBiasaYG+RQzmQ8=,tag:Rt2RzNbO4qhKDsbhwPyVfQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQVJ1czIwOUVEU2tkTVZj
            VjJ2Ni9WeVZBNXBwbFZCc1hJaXNiaE5ZdWtNCjExWUZaVlU1Zk1laUR0V1dSaS9t
            UG5BMUJ4Z3doZGtIVGZPNGNXUXRMTmMKLS0tIGtST2FuT29Vbk9VdUJJQ2VRYy83
            eHVnZjN4S3doOE9ZdGdrZ04ydDFsZkkKy6nrOKF3kIchutTk8lJj5kXzcPoYJllc
            hpYDvhdBPRDONYX5TDKqJ/EcWvKwEBeviczbdZVddvafnTf0MY0HcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T20:03:25Z"
    mac: ENC[AES256_GCM,data:0LxGIlGdrbpHmaG8BU19ZNuIBeX8x6cnvVrLGpt+7D4uupzggMgU9FnKwMNtWL56uj5gGZXDrLf3nieRJeIdO7Scy87Euwb7WX/gzjkJ74MSIopxc2zunta4owltndWMQQdnmQ7ZQRx+iKbfL7SYzR7gjJsIcEiVgheZDlytYlA=,iv:xav73ah0O9zwFWvFtpcqMY7O/AhdIDFh+uyYLjofv0M=,tag:8g3a6330yVAhfqLiixejYQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
