apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-creds
    namespace: traefik-system
stringData:
    client-id: ENC[AES256_GCM,data:2JGjXpIT6plKaRm3flAT4s9f,iv:F9w+jAl84sFFTw/4sDmUgqGklpfEd4JPfFG1T6AyWJs=,tag:xm+f98qDEojvgVm0oVuvqg==,type:str]
    client-secret: ENC[AES256_GCM,data:HUEWuGK0gDV7NuZDzpHgutQp+OIAh79uskArMs/v8e1jEOqz4Ls2Movpj3l6DEuPjLsCknz4WVKwRFFGgZ0Plw==,iv:TKGVBvT7hUpww88cFf0I7IgnRjZshbGsPGe/nJqomfw=,tag:tAjIvQhuWuv97m2L/45O4g==,type:str]
    cookie-secret: ENC[AES256_GCM,data:RP/DmTKU3w5hLzK6hv0YPVKjtgRxa5DF5Wn5Z1y1278H8dE3ssOVDYp2JN4PyIkeAlQEnXvAApX9/dSfRD9kzA==,iv:d+Y5H325vbJcLrVlNSEkxOAwfW6kjxx+iBW/7jWK9y4=,tag:2s3DKqrF150bj19T3HgLGQ==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwR09uTHRvVXdyY1BFTEZu
            Y0lpRENySUtQaUdRSUZ1eExpeERhdWIzTkJVClRlVzVxRUlDOVRVZW9lM2hkaVNr
            aXdRcXhoUmZZZGkyR1lmRGN0N283VnMKLS0tIHNNVnJMSlp0a1Vhcks3ODJ1UW1y
            SVdkLyt5elJDVVJ3M3FQWlVVL2JRWGsKURQvizcQ+ZEnHRyJ/o0m8toOwmNtbdRb
            xhNCfZD90wO8+ZCudddKgQsnPWnHB9yHr4pClzfyMHkfIOpqEKz6Ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T19:18:41Z"
    mac: ENC[AES256_GCM,data:lKf5UVOZaoO//JCWnUgjFX/vxhwJ6IkhirN2+Huq4O+auEcAZWLf+yT99v9vh53bdYTysNBYm46SZ1tTO6iVhvoD+vBHvjtOjCgG/xdfedCkKHhKLqPPSy1PwtzdfUh0Iu/2WmdqdoZgHUt7y3lhpS3rpXVJ05oGUFmjZ+QgDBg=,iv:767oBmlztYipMuMChxfJdOvQEfMMz+56kndnqr760R8=,tag:z3hLsiUAH2WrsuZXhwOiUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
