---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 1h
  url: https://oauth2-proxy.github.io/manifests
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: oauth2-proxy
      version: "10.x.x"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
  targetNamespace: traefik-system
  install:
    createNamespace: true
  values:
    config:
      existingSecret: oauth2-proxy-creds
      configFile: |-
        email_domains = ["*"]
        upstreams = [ "static://200" ]
        reverse_proxy = true
    extraArgs:
      provider: oidc
      oidc-issuer-url: https://auth.emoh.pl
      cookie-domain: .emoh.pl
      whitelist-domain: .emoh.pl
      cookie-secure: true
      cookie-samesite: lax
      skip-provider-button: true
      oidc-groups-claim: roles
      allowed-group: admin
    ingress:
      enabled: true
      className: traefik-system-traefik
      hosts:
        - sso.emoh.pl
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi
