apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-creds
    namespace: traefik-system
stringData:
    client-id: ENC[AES256_GCM,data:KMIGa/CusCRjBtrImcf808b+,iv:Z/RhzPYqyW6AoZErhbjpzcIbFwx1VjVBU6eTqMZE1CM=,tag:IwOHuB5ERS7drVY3Ey5dig==,type:str]
    client-secret: ENC[AES256_GCM,data:IwQ3Ctqx9WDpUSMkNeXbXz6MlASA3Bm6w4D0OjBh9w/VQ8J10LtCrfku+3vZFSBjlf7QU3Q2j3+lo9PhMjW2og==,iv:C87Kgk2qCBj2epoVXjP0WONOzeLnnk66N3ga7Nbs6ts=,tag:SNlPjXp+h/wJxdUe5MmCCg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:c+qYnBzWq4zQAMzH0PHk6hQF7IbU4mVWvXDrbpwdSSyCdK5r6sM26JhXDDQ=,iv:qq30ZRCjF4r9ZZtPLFVIxSLc7twJNaXM4DE6A1IiK3A=,tag:yR0JvXFBo0qlfp2+VK57Eg==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxbFY4djN0dWExbDJEeFdZ
            bkE1enAyWjdvck5nR3ZCRmc1VXFub2FsUjAwCmNSQ1lER1hRQXVxRTA4aXZtR1Fn
            QVlaSjlYeE1LSW9obDIyN09JMmtKeXcKLS0tIGsxcmNUT3ZyS2VkUkk4aWhRcXNN
            ODQzemhSeFdaRURIbElyYlVTbjREWEUKdEz1w7TiVoSzfAlGOhTwGDkT48qBKDVV
            nUvSNNuAF6GJ9CRbUWMDWzfwfFfLfrYG//J446cVMhxOe+Fc2Fm9sA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T18:04:39Z"
    mac: ENC[AES256_GCM,data:GniKglIbl25ZGaTU2KPD7gbMvaElrxIz48qn1MzLnfW0TTpTSLjWsMOgVsp45mOw977nWuELJElHhMgmLHWesnc1j+IHMxY01zXf2ruth2MuoTKu22MxVyap/sOVjAVm98RuxLbbLPwYnMbuB383ZaPVbwHiVWQykgHjVzs3Spw=,iv:34KC47kzBep2KpqNKWDaWhtEOWpgNxvJfGzX8SJEw+Y=,tag:92bgX37aX7DMTEKk5xCuxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
