apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-creds
    namespace: traefik-system
stringData:
    client-id: ENC[AES256_GCM,data:Gx7M7aOgwO9R9Ul1ygs56RMu,iv:9JiFiVgwicc09D+qI5rkCkO9vxmicp3nC9oTEVJPciQ=,tag:wLsWb3mqbU4uoHO1igLalg==,type:str]
    client-secret: ENC[AES256_GCM,data:33Gar0R0Fmuy1rzpTEBfuPh0iMNkC55P3E+aDxRYAt+bizQyE906exW6ysGgknyJZmKGQNYWBdun+WQOEjTa9w==,iv:u3/dvk8HTh6rY1Zb+LtaYbcosLsk9ca+JeWONmxiAko=,tag:2JNAPatfrK4QQYybBQ94UA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:OlQLGxmt53FmEP0dAKr0fdhOHFfhBCJVkxys9kJonQEltatfX3+mx4Hb0/E=,iv:7gURqY/J8IwQqUZcZxbSdkBKuqh7AIzQfghhI4kU41A=,tag:jj850T4/Bkv4Xt97Z6MI/w==,type:str]
sops:
    age:
        - recipient: age1cwwxvkg5r930j5y6vj3uu33tstmpdgwhv8uxq62vherkfwktu50qag25hr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnakxhYTdkQTZockNWMWQ4
            OFo2YXZaRHV3b2NTTUt1UTZEclRaendYRVFRCnpMbEhrMG5HN1VWQ1ZPcGtJNUlX
            S0ZwNzI0cHpDcjVWT3BZWlU2ZHc0WjQKLS0tIGFSVSt3UGF4VDk0NmdjN2E2UVhw
            Ky93RFJMY3d1dFQraVRIbWt2cHdHYUUKNRpiCjhu0vNVRnV+0u6qvoz7elFIapZy
            UFUmM5sRFsMb38+pgzAi6dvdU0xmVUhYlBiy+r3wQQUCfSrt9ElhgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-07T15:34:09Z"
    mac: ENC[AES256_GCM,data:ktBJs2CfkAgNijJuxGymh+IasFQgRQbJT4nTnQy2tX+L4GYMXP/M098NWC+34IGCcznqcghVQMDgdYWTab7yPuxatDx4D2ZzllUqOQQb76l32rtmUiWPUN623NTDXEsiR7Ql9/+YBwspZttnhzr4oJs21IFKEhySlGXD+h6n/Ic=,iv:J1XS2K4Ps6ZTAmlbrryM0szPlVKZxuay+ZXNjCykSPo=,tag:gxLp0L3c2c5ilKAWK/JTIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
